// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_comp_BackToMainWindowBtn7_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Music_Item_create_hook(lv_obj_t * comp)
{
}

void ui_comp_MusicList_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Music_List_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Header_Volume_create_hook(lv_obj_t * comp)
{
}
