// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: settings

#ifndef _SETTINGS_UI_H
#define _SETTINGS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
void ui_event_Settings( lv_event_t * e);
extern lv_obj_t *ui_Settings;
extern lv_obj_t *ui_Header_Main2;
extern lv_obj_t *ui_Header_Main_Text2;
extern lv_obj_t *ui_Header_Main_Time2;
extern lv_obj_t *ui_Header_Main_Volume_Icon2;
extern lv_obj_t *ui_Header_Main_Volume_Value2;
extern lv_obj_t *ui_Settings_List;
extern lv_obj_t *ui_Settings_Backlight;
extern lv_obj_t *ui_Settings_Backlight_Text;
extern lv_obj_t *ui_Settings_Backlight_Line;
extern lv_obj_t *ui_Settings_Backlight_Icon;
extern lv_obj_t *ui_Settings_Backlight_Decora_Icon;
void ui_event_Settings_Backlight_Btn( lv_event_t * e);
extern lv_obj_t *ui_Settings_Backlight_Btn;
extern lv_obj_t *ui_Settings_Bluetooth;
extern lv_obj_t *ui_Settings_Bluetooth_Text;
extern lv_obj_t *ui_Settings_Bluetooth_Line;
extern lv_obj_t *ui_Settings_Bluetooth_Icon;
extern lv_obj_t *ui_Settings_Bluetooth_Decora_Icon;
void ui_event_Settings_Bluetooth_Btn( lv_event_t * e);
extern lv_obj_t *ui_Settings_Bluetooth_Btn;
extern lv_obj_t *ui_Settings_Time;
extern lv_obj_t *ui_Settings_Time_Text;
extern lv_obj_t *ui_Settings_Time_Line;
extern lv_obj_t *ui_Settings_Time_Icon;
extern lv_obj_t *ui_Settings_Time_Decora_Icon;
void ui_event_Settings_Time_Btn( lv_event_t * e);
extern lv_obj_t *ui_Settings_Time_Btn;
extern lv_obj_t *ui_Settings_ID;
extern lv_obj_t *ui_Settings_ID_Text;
extern lv_obj_t *ui_Settings_ID_Line;
extern lv_obj_t *ui_Settings_ID_Icon;
extern lv_obj_t *ui_Settings_ID_Decora_Icon;
void ui_event_Settings_ID_Btn( lv_event_t * e);
extern lv_obj_t *ui_Settings_ID_Btn;
extern lv_obj_t *ui_Settings_Default_Volume;
extern lv_obj_t *ui_Settings_Default_Volume_Text;
extern lv_obj_t *ui_Settings_Default_Volume_Line;
extern lv_obj_t *ui_Settings_Default_Volume_Icon;
extern lv_obj_t *ui_Settings_Default_Volume_Decora_Icon;
void ui_event_Settings_Default_Volume_Btn( lv_event_t * e);
extern lv_obj_t *ui_Settings_Default_Volume_Btn;
extern lv_obj_t *ui_Settings_Max_Volume;
extern lv_obj_t *ui_Settings_Max_Volume_Text;
extern lv_obj_t *ui_Settings_Max_Volume_Line;
extern lv_obj_t *ui_Settings_Max_Volume_Icon;
extern lv_obj_t *ui_Settings_Max_Volume_Decora_Icon;
void ui_event_Settings_Max_Volume_Btn( lv_event_t * e);
extern lv_obj_t *ui_Settings_Max_Volume_Btn;
extern lv_obj_t *ui_BackToMainWindow2;
extern lv_obj_t *ui_Default_Volume_Panel;
extern lv_obj_t *ui_Default_Volume_Text;
void ui_event_Default_Volume_Verify_Btn( lv_event_t * e);
extern lv_obj_t *ui_Default_Volume_Verify_Btn;
extern lv_obj_t *ui_Default_Volume_Verify_Btn_Text;
void ui_event_Default_Volume_Cancel_Btn( lv_event_t * e);
extern lv_obj_t *ui_Default_Volume_Cancel_Btn;
extern lv_obj_t *ui_Default_Volume_Cancel_Text;
extern lv_obj_t *ui_Default_Volume_Value_Panel;
extern lv_obj_t *ui_Default_Volume_Value;
void ui_event_Default_Volume_Dec_Btn( lv_event_t * e);
extern lv_obj_t *ui_Default_Volume_Dec_Btn;
extern lv_obj_t *ui_Default_Volume_Dec_Icon;
void ui_event_Default_Volume_Add_Btn( lv_event_t * e);
extern lv_obj_t *ui_Default_Volume_Add_Btn;
extern lv_obj_t *ui_Default_Volume_Add_Icon;
extern lv_obj_t *ui_Max_Volume_Panel;
extern lv_obj_t *ui_Max_Volume_Text;
void ui_event_Max_Volume_Verify_Btn( lv_event_t * e);
extern lv_obj_t *ui_Max_Volume_Verify_Btn;
extern lv_obj_t *ui_Max_Volume_Verify_Icon;
void ui_event_Max_Volume_Cancel_Btn( lv_event_t * e);
extern lv_obj_t *ui_Max_Volume_Cancel_Btn;
extern lv_obj_t *ui_Max_Volume_Cancel_Text;
extern lv_obj_t *ui_Max_Volume_Value_Panel;
extern lv_obj_t *ui_Max_Volume_Value;
void ui_event_Max_Volume_Dec_Btn( lv_event_t * e);
extern lv_obj_t *ui_Max_Volume_Dec_Btn;
extern lv_obj_t *ui_Max_Volume_Dec_Icon;
void ui_event_Max_Volume_Add_Btn( lv_event_t * e);
extern lv_obj_t *ui_Max_Volume_Add_Btn;
extern lv_obj_t *ui_Max_Volume_Add_Icon;
// SCREEN: ui_Backlight_Settings
void ui_Backlight_Settings_screen_init(void);
extern lv_obj_t *ui_Backlight_Settings;
extern lv_obj_t *ui_Header_Main3;
extern lv_obj_t *ui_Header_Main_Text3;
extern lv_obj_t *ui_Header_Main_Time3;
extern lv_obj_t *ui_Header_Main_Volume_Icon3;
extern lv_obj_t *ui_Header_Main_Volume_Value3;
void ui_event_BackToMainWindow3( lv_event_t * e);
extern lv_obj_t *ui_BackToMainWindow3;
extern lv_obj_t *ui_Backlight_Settings_items;
extern lv_obj_t *ui_Backlight_Brightness;
extern lv_obj_t *ui_Backlight_Brightness_Text;
extern lv_obj_t *ui_Backlight_Brightness_Line;
void ui_event_Backlight_Brightness_Btn( lv_event_t * e);
extern lv_obj_t *ui_Backlight_Brightness_Btn;
extern lv_obj_t *ui_Backlight_Time;
extern lv_obj_t *ui_Backlight_Time_Text;
extern lv_obj_t *ui_Backlight_Time_Line;
void ui_event_Backlight_Time_Btn( lv_event_t * e);
extern lv_obj_t *ui_Backlight_Time_Btn;
extern lv_obj_t *ui_Backlight_Brightness_Panel;
extern lv_obj_t *ui_Backlight_Brightness_Panel_Text;
void ui_event_Backlight_Brightness_Verify_Btn( lv_event_t * e);
extern lv_obj_t *ui_Backlight_Brightness_Verify_Btn;
extern lv_obj_t *ui_Backlight_Brightness_Verify_Btn_Text;
void ui_event_Backlight_Brightness_Cancel_Btn( lv_event_t * e);
extern lv_obj_t *ui_Backlight_Brightness_Cancel_Btn;
extern lv_obj_t *ui_Backlight_Brightness_Cancel_Text;
extern lv_obj_t *ui_Backlight_Brightness_Value_Panel;
extern lv_obj_t *ui_Backlight_Brightness_Value;
void ui_event_Backlight_Brightness_Dec_Btn( lv_event_t * e);
extern lv_obj_t *ui_Backlight_Brightness_Dec_Btn;
extern lv_obj_t *ui_Backlight_Brightness_Dec_Icon;
void ui_event_Backlight_Brightness_Add_Btn( lv_event_t * e);
extern lv_obj_t *ui_Backlight_Brightness_Add_Btn;
extern lv_obj_t *ui_Backlight_Brightness_Add_Icon;
extern lv_obj_t *ui_Backlight_Time_Panel;
extern lv_obj_t *ui_Backlight_Time_Panel_Text;
void ui_event_Backlight_Time_Verify_Btn( lv_event_t * e);
extern lv_obj_t *ui_Backlight_Time_Verify_Btn;
extern lv_obj_t *ui_Backlight_Time_Verify_Btn_Text;
void ui_event_Backlight_Time_Cancel_Btn( lv_event_t * e);
extern lv_obj_t *ui_Backlight_Time_Cancel_Btn;
extern lv_obj_t *ui_Backlight_Time_Cancel_Text;
extern lv_obj_t *ui_Backlight_Time_Value_Panel;
extern lv_obj_t *ui_Backlight_Time_Value;
void ui_event_Backlight_Time_Dec_Btn( lv_event_t * e);
extern lv_obj_t *ui_Backlight_Time_Dec_Btn;
extern lv_obj_t *ui_Backlight_Time_Dec_Icon;
void ui_event_Backlight_Time_Add_Btn( lv_event_t * e);
extern lv_obj_t *ui_Backlight_Time_Add_Btn;
extern lv_obj_t *ui_Backlight_Time_Add_Icon;
// SCREEN: ui_Bluetooth_Settings
void ui_Bluetooth_Settings_screen_init(void);
extern lv_obj_t *ui_Bluetooth_Settings;
extern lv_obj_t *ui_Header_Main4;
extern lv_obj_t *ui_Header_Main_Text4;
extern lv_obj_t *ui_Header_Main_Time4;
extern lv_obj_t *ui_Header_Main_Volume_Icon4;
extern lv_obj_t *ui_Header_Main_Volume_Value4;
extern lv_obj_t *ui_Bluetooth_Name;
extern lv_obj_t *ui_Bluetooth_Name_Text;
extern lv_obj_t *ui_Bluetooth_Name_Line;
void ui_event_Bluetooth_Name_Input( lv_event_t * e);
extern lv_obj_t *ui_Bluetooth_Name_Input;
void ui_event_Bluetooth_Name_Enter_Btn( lv_event_t * e);
extern lv_obj_t *ui_Bluetooth_Name_Enter_Btn;
extern lv_obj_t *ui_Bluetooth_Name_Enter_Icon;
extern lv_obj_t *ui_Bluetooth_Password;
extern lv_obj_t *ui_Bluetooth_Password_Text;
extern lv_obj_t *ui_Bluetooth_Password_Line;
void ui_event_Bluetooth_Password_Input( lv_event_t * e);
extern lv_obj_t *ui_Bluetooth_Password_Input;
void ui_event_Bluetooth_Password_Enter_Btn( lv_event_t * e);
extern lv_obj_t *ui_Bluetooth_Password_Enter_Btn;
extern lv_obj_t *ui_Bluetooth_Password_Enter_Icon;
extern lv_obj_t *ui_Bluetooth_Keyboard;
void ui_event_BackToMainWindow4( lv_event_t * e);
extern lv_obj_t *ui_BackToMainWindow4;
// SCREEN: ui_Time_Settings
void ui_Time_Settings_screen_init(void);
extern lv_obj_t *ui_Time_Settings;
extern lv_obj_t *ui_Header_Main5;
extern lv_obj_t *ui_Header_Main_Text5;
extern lv_obj_t *ui_Header_Main_Time5;
extern lv_obj_t *ui_Header_Main_Volume_Icon5;
extern lv_obj_t *ui_Header_Main_Volume_Value5;
extern lv_obj_t *ui_Time_Setting_Panel;
extern lv_obj_t *ui_Time_Setting_Text;
extern lv_obj_t *ui_Time_Setting_Line;
void ui_event_Time_Setting_Hour( lv_event_t * e);
extern lv_obj_t *ui_Time_Setting_Hour;
void ui_event_Time_Setting_Min( lv_event_t * e);
extern lv_obj_t *ui_Time_Setting_Min;
void ui_event_Time_Setting_Enter_Btn( lv_event_t * e);
extern lv_obj_t *ui_Time_Setting_Enter_Btn;
extern lv_obj_t *ui_Time_Setting_Enter_Icon;
extern lv_obj_t *ui_Date_Setting_Panel;
extern lv_obj_t *ui_Date_Settings_Text;
extern lv_obj_t *ui_Date_Setting_Line;
void ui_event_Date_Setting_Year( lv_event_t * e);
extern lv_obj_t *ui_Date_Setting_Year;
void ui_event_Date_Setting_Month( lv_event_t * e);
extern lv_obj_t *ui_Date_Setting_Month;
void ui_event_Date_Setting_Day( lv_event_t * e);
extern lv_obj_t *ui_Date_Setting_Day;
void ui_event_Date_Setting_Enter_Btn( lv_event_t * e);
extern lv_obj_t *ui_Date_Setting_Enter_Btn;
extern lv_obj_t *ui_Date_Setting_Enter_Icon;
extern lv_obj_t *ui_Date_Time_Keyboard;
void ui_event_BackToMainWindow5( lv_event_t * e);
extern lv_obj_t *ui_BackToMainWindow5;
// SCREEN: ui_ID_Settings
void ui_ID_Settings_screen_init(void);
extern lv_obj_t *ui_ID_Settings;
extern lv_obj_t *ui_Header_Main6;
extern lv_obj_t *ui_Header_Main_Text6;
extern lv_obj_t *ui_Header_Main_Time6;
extern lv_obj_t *ui_Header_Main_Volume_Icon6;
extern lv_obj_t *ui_Header_Main_Volume_Value6;
extern lv_obj_t *ui_ID_Keyboard;
void ui_event_ID_Setting_Input( lv_event_t * e);
extern lv_obj_t *ui_ID_Setting_Input;
void ui_event_ID_Setting_Enter_Btn( lv_event_t * e);
extern lv_obj_t *ui_ID_Setting_Enter_Btn;
extern lv_obj_t *ui_ID_Setting_Enter_Icon;
void ui_event_BackToMainWindow6( lv_event_t * e);
extern lv_obj_t *ui_BackToMainWindow6;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_861711258);   // assets/丽枫UI/background.png
LV_IMG_DECLARE( ui_img_490182776);   // assets/丽枫UI/音量.png
LV_IMG_DECLARE( ui_img_149594991);   // assets/丽枫UI/背光设置.png
LV_IMG_DECLARE( ui_img_1830113796);   // assets/丽枫UI/back32.png
LV_IMG_DECLARE( ui_img_1711952528);   // assets/丽枫UI/蓝牙设置.png
LV_IMG_DECLARE( ui_img_1422805608);   // assets/丽枫UI/时间设置.png
LV_IMG_DECLARE( ui_img_728059867);   // assets/丽枫UI/ID设置.png
LV_IMG_DECLARE( ui_img_348826415);   // assets/丽枫UI/back.png
LV_IMG_DECLARE( ui_img_404002205);   // assets/丽枫UI/Left triangle40.png
LV_IMG_DECLARE( ui_img_239308628);   // assets/丽枫UI/Right triangle40.png
LV_IMG_DECLARE( ui_img_404002205);   // assets/丽枫UI/Left triangle40.png
LV_IMG_DECLARE( ui_img_239308628);   // assets/丽枫UI/Right triangle40.png
LV_IMG_DECLARE( ui_img_861711258);   // assets/丽枫UI/background.png
LV_IMG_DECLARE( ui_img_1260392355);   // assets/丽枫UI/yes.png
LV_IMG_DECLARE( ui_img_1830113796);   // assets/丽枫UI/back32.png


LV_FONT_DECLARE( ui_font_LanTIng20);
LV_FONT_DECLARE( ui_font_LanTing18);
LV_FONT_DECLARE( ui_font_LanTingFine18);
LV_FONT_DECLARE( ui_font_LanTingFine22);
LV_FONT_DECLARE( ui_font_LanTingFine24);
LV_FONT_DECLARE( ui_font_LanTing40);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
