// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Settings_Window_screen_init(void)
{
ui_Settings_Window = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Settings_Window, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Settings_Window, &ui_img_861711258, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Header_Main2 = lv_obj_create(ui_Settings_Window);
lv_obj_remove_style_all(ui_Header_Main2);
lv_obj_set_height( ui_Header_Main2, 30);
lv_obj_set_width( ui_Header_Main2, lv_pct(100));
lv_obj_set_x( ui_Header_Main2, 0 );
lv_obj_set_y( ui_Header_Main2, -225 );
lv_obj_set_align( ui_Header_Main2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Header_Main2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Header_Main_Text2 = lv_label_create(ui_Header_Main2);
lv_obj_set_width( ui_Header_Main_Text2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Main_Text2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Header_Main_Text2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Header_Main_Text2,"设置");
lv_obj_set_style_text_color(ui_Header_Main_Text2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Main_Text2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Header_Main_Text2, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Main_Volume_Icon2 = lv_img_create(ui_Header_Main2);
lv_img_set_src(ui_Header_Main_Volume_Icon2, &ui_img_490182776);
lv_obj_set_width( ui_Header_Main_Volume_Icon2, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_Header_Main_Volume_Icon2, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_Header_Main_Volume_Icon2, 160 );
lv_obj_set_y( ui_Header_Main_Volume_Icon2, 0 );
lv_obj_set_align( ui_Header_Main_Volume_Icon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Header_Main_Volume_Icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Header_Main_Volume_Icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Header_Main_Volume_Value2 = lv_label_create(ui_Header_Main2);
lv_obj_set_width( ui_Header_Main_Volume_Value2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Main_Volume_Value2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Main_Volume_Value2, 415 );
lv_obj_set_y( ui_Header_Main_Volume_Value2, 0 );
lv_obj_set_align( ui_Header_Main_Volume_Value2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Header_Main_Volume_Value2,"79");
lv_obj_set_style_text_color(ui_Header_Main_Volume_Value2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Main_Volume_Value2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Header_Main_Volume_Value2, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings_List2 = lv_obj_create(ui_Settings_Window);
lv_obj_remove_style_all(ui_Settings_List2);
lv_obj_set_width( ui_Settings_List2, 480);
lv_obj_set_height( ui_Settings_List2, 423);
lv_obj_set_x( ui_Settings_List2, 0 );
lv_obj_set_y( ui_Settings_List2, 26 );
lv_obj_set_align( ui_Settings_List2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_List2, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_Settings_Backlight2 = lv_obj_create(ui_Settings_List2);
lv_obj_remove_style_all(ui_Settings_Backlight2);
lv_obj_set_width( ui_Settings_Backlight2, 480);
lv_obj_set_height( ui_Settings_Backlight2, 70);
lv_obj_set_x( ui_Settings_Backlight2, 0 );
lv_obj_set_y( ui_Settings_Backlight2, -180 );
lv_obj_set_align( ui_Settings_Backlight2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Backlight2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Backlight_Text2 = lv_label_create(ui_Settings_Backlight2);
lv_obj_set_width( ui_Settings_Backlight_Text2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Backlight_Text2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Backlight_Text2, 80 );
lv_obj_set_y( ui_Settings_Backlight_Text2, 0 );
lv_obj_set_align( ui_Settings_Backlight_Text2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Settings_Backlight_Text2,"背光设置");
lv_obj_set_style_text_color(ui_Settings_Backlight_Text2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Settings_Backlight_Text2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Settings_Backlight_Text2, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings_Backlight_Line2 = lv_obj_create(ui_Settings_Backlight2);
lv_obj_set_width( ui_Settings_Backlight_Line2, 450);
lv_obj_set_height( ui_Settings_Backlight_Line2, 3);
lv_obj_set_x( ui_Settings_Backlight_Line2, -1 );
lv_obj_set_y( ui_Settings_Backlight_Line2, 30 );
lv_obj_set_align( ui_Settings_Backlight_Line2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Backlight_Line2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Backlight_Icon2 = lv_img_create(ui_Settings_Backlight2);
lv_img_set_src(ui_Settings_Backlight_Icon2, &ui_img_149594991);
lv_obj_set_width( ui_Settings_Backlight_Icon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Backlight_Icon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Backlight_Icon2, -185 );
lv_obj_set_y( ui_Settings_Backlight_Icon2, 0 );
lv_obj_set_align( ui_Settings_Backlight_Icon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Backlight_Icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Backlight_Icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Backlight_Decora_Icon2 = lv_img_create(ui_Settings_Backlight2);
lv_img_set_src(ui_Settings_Backlight_Decora_Icon2, &ui_img_1830113796);
lv_obj_set_width( ui_Settings_Backlight_Decora_Icon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Backlight_Decora_Icon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Backlight_Decora_Icon2, 210 );
lv_obj_set_y( ui_Settings_Backlight_Decora_Icon2, 5 );
lv_obj_set_align( ui_Settings_Backlight_Decora_Icon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Backlight_Decora_Icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Backlight_Decora_Icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Settings_Backlight_Decora_Icon2,1800);

ui_Settings_Backlight_Btn2 = lv_btn_create(ui_Settings_Backlight2);
lv_obj_set_width( ui_Settings_Backlight_Btn2, 480);
lv_obj_set_height( ui_Settings_Backlight_Btn2, 70);
lv_obj_set_align( ui_Settings_Backlight_Btn2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Backlight_Btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Settings_Backlight_Btn2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings_Backlight_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings_Backlight_Btn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Settings_Backlight_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Settings_Backlight_Btn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Settings_Backlight_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Settings_Backlight_Btn2, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Settings_Bluetooth2 = lv_obj_create(ui_Settings_List2);
lv_obj_remove_style_all(ui_Settings_Bluetooth2);
lv_obj_set_width( ui_Settings_Bluetooth2, 480);
lv_obj_set_height( ui_Settings_Bluetooth2, 70);
lv_obj_set_x( ui_Settings_Bluetooth2, 0 );
lv_obj_set_y( ui_Settings_Bluetooth2, -110 );
lv_obj_set_align( ui_Settings_Bluetooth2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Bluetooth2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Bluetooth_Text2 = lv_label_create(ui_Settings_Bluetooth2);
lv_obj_set_width( ui_Settings_Bluetooth_Text2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Bluetooth_Text2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Bluetooth_Text2, 80 );
lv_obj_set_y( ui_Settings_Bluetooth_Text2, 0 );
lv_obj_set_align( ui_Settings_Bluetooth_Text2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Settings_Bluetooth_Text2,"蓝牙设置");
lv_obj_set_style_text_color(ui_Settings_Bluetooth_Text2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Settings_Bluetooth_Text2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Settings_Bluetooth_Text2, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings_Bluetooth_Line2 = lv_obj_create(ui_Settings_Bluetooth2);
lv_obj_set_width( ui_Settings_Bluetooth_Line2, 450);
lv_obj_set_height( ui_Settings_Bluetooth_Line2, 3);
lv_obj_set_x( ui_Settings_Bluetooth_Line2, -1 );
lv_obj_set_y( ui_Settings_Bluetooth_Line2, 30 );
lv_obj_set_align( ui_Settings_Bluetooth_Line2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Bluetooth_Line2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Bluetooth_Icon2 = lv_img_create(ui_Settings_Bluetooth2);
lv_img_set_src(ui_Settings_Bluetooth_Icon2, &ui_img_1711952528);
lv_obj_set_width( ui_Settings_Bluetooth_Icon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Bluetooth_Icon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Bluetooth_Icon2, -185 );
lv_obj_set_y( ui_Settings_Bluetooth_Icon2, 0 );
lv_obj_set_align( ui_Settings_Bluetooth_Icon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Bluetooth_Icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Bluetooth_Icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Bluetooth_Decora_Icon2 = lv_img_create(ui_Settings_Bluetooth2);
lv_img_set_src(ui_Settings_Bluetooth_Decora_Icon2, &ui_img_1830113796);
lv_obj_set_width( ui_Settings_Bluetooth_Decora_Icon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Bluetooth_Decora_Icon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Bluetooth_Decora_Icon2, 210 );
lv_obj_set_y( ui_Settings_Bluetooth_Decora_Icon2, 5 );
lv_obj_set_align( ui_Settings_Bluetooth_Decora_Icon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Bluetooth_Decora_Icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Bluetooth_Decora_Icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Settings_Bluetooth_Decora_Icon2,1800);

ui_Settings_Bluetooth_Btn2 = lv_btn_create(ui_Settings_Bluetooth2);
lv_obj_set_width( ui_Settings_Bluetooth_Btn2, 480);
lv_obj_set_height( ui_Settings_Bluetooth_Btn2, 70);
lv_obj_set_align( ui_Settings_Bluetooth_Btn2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Bluetooth_Btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Settings_Bluetooth_Btn2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings_Bluetooth_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings_Bluetooth_Btn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Settings_Bluetooth_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Settings_Bluetooth_Btn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Settings_Bluetooth_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Settings_Bluetooth_Btn2, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Settings_Time2 = lv_obj_create(ui_Settings_List2);
lv_obj_remove_style_all(ui_Settings_Time2);
lv_obj_set_width( ui_Settings_Time2, 480);
lv_obj_set_height( ui_Settings_Time2, 70);
lv_obj_set_x( ui_Settings_Time2, 0 );
lv_obj_set_y( ui_Settings_Time2, -40 );
lv_obj_set_align( ui_Settings_Time2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Time2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Time_Text2 = lv_label_create(ui_Settings_Time2);
lv_obj_set_width( ui_Settings_Time_Text2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Time_Text2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Time_Text2, 80 );
lv_obj_set_y( ui_Settings_Time_Text2, 0 );
lv_obj_set_align( ui_Settings_Time_Text2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Settings_Time_Text2,"时间设置");
lv_obj_set_style_text_color(ui_Settings_Time_Text2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Settings_Time_Text2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Settings_Time_Text2, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings_Time_Line2 = lv_obj_create(ui_Settings_Time2);
lv_obj_set_width( ui_Settings_Time_Line2, 450);
lv_obj_set_height( ui_Settings_Time_Line2, 3);
lv_obj_set_x( ui_Settings_Time_Line2, -1 );
lv_obj_set_y( ui_Settings_Time_Line2, 30 );
lv_obj_set_align( ui_Settings_Time_Line2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Time_Line2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Time_Icon2 = lv_img_create(ui_Settings_Time2);
lv_img_set_src(ui_Settings_Time_Icon2, &ui_img_1422805608);
lv_obj_set_width( ui_Settings_Time_Icon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Time_Icon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Time_Icon2, -185 );
lv_obj_set_y( ui_Settings_Time_Icon2, 0 );
lv_obj_set_align( ui_Settings_Time_Icon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Time_Icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Time_Icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Time_Decora_Icon2 = lv_img_create(ui_Settings_Time2);
lv_img_set_src(ui_Settings_Time_Decora_Icon2, &ui_img_1830113796);
lv_obj_set_width( ui_Settings_Time_Decora_Icon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Time_Decora_Icon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Time_Decora_Icon2, 210 );
lv_obj_set_y( ui_Settings_Time_Decora_Icon2, 5 );
lv_obj_set_align( ui_Settings_Time_Decora_Icon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Time_Decora_Icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Time_Decora_Icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Settings_Time_Decora_Icon2,1800);

ui_Settings_Time_Btn2 = lv_btn_create(ui_Settings_Time2);
lv_obj_set_width( ui_Settings_Time_Btn2, 480);
lv_obj_set_height( ui_Settings_Time_Btn2, 70);
lv_obj_set_align( ui_Settings_Time_Btn2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Time_Btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Settings_Time_Btn2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings_Time_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings_Time_Btn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Settings_Time_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Settings_Time_Btn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Settings_Time_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Settings_Time_Btn2, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Settings_ID2 = lv_obj_create(ui_Settings_List2);
lv_obj_remove_style_all(ui_Settings_ID2);
lv_obj_set_width( ui_Settings_ID2, 480);
lv_obj_set_height( ui_Settings_ID2, 70);
lv_obj_set_x( ui_Settings_ID2, 0 );
lv_obj_set_y( ui_Settings_ID2, 30 );
lv_obj_set_align( ui_Settings_ID2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_ID2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_ID_Text2 = lv_label_create(ui_Settings_ID2);
lv_obj_set_width( ui_Settings_ID_Text2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_ID_Text2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_ID_Text2, 80 );
lv_obj_set_y( ui_Settings_ID_Text2, 0 );
lv_obj_set_align( ui_Settings_ID_Text2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Settings_ID_Text2,"ID设置");
lv_obj_set_style_text_color(ui_Settings_ID_Text2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Settings_ID_Text2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Settings_ID_Text2, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings_ID_Line2 = lv_obj_create(ui_Settings_ID2);
lv_obj_set_width( ui_Settings_ID_Line2, 450);
lv_obj_set_height( ui_Settings_ID_Line2, 3);
lv_obj_set_x( ui_Settings_ID_Line2, -1 );
lv_obj_set_y( ui_Settings_ID_Line2, 30 );
lv_obj_set_align( ui_Settings_ID_Line2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_ID_Line2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_ID_Icon2 = lv_img_create(ui_Settings_ID2);
lv_img_set_src(ui_Settings_ID_Icon2, &ui_img_728059867);
lv_obj_set_width( ui_Settings_ID_Icon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_ID_Icon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_ID_Icon2, -185 );
lv_obj_set_y( ui_Settings_ID_Icon2, 0 );
lv_obj_set_align( ui_Settings_ID_Icon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_ID_Icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_ID_Icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_ID_Decora_Icon2 = lv_img_create(ui_Settings_ID2);
lv_img_set_src(ui_Settings_ID_Decora_Icon2, &ui_img_1830113796);
lv_obj_set_width( ui_Settings_ID_Decora_Icon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_ID_Decora_Icon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_ID_Decora_Icon2, 210 );
lv_obj_set_y( ui_Settings_ID_Decora_Icon2, 5 );
lv_obj_set_align( ui_Settings_ID_Decora_Icon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_ID_Decora_Icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_ID_Decora_Icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Settings_ID_Decora_Icon2,1800);

ui_Settings_ID_Btn2 = lv_btn_create(ui_Settings_ID2);
lv_obj_set_width( ui_Settings_ID_Btn2, 480);
lv_obj_set_height( ui_Settings_ID_Btn2, 70);
lv_obj_set_align( ui_Settings_ID_Btn2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_ID_Btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Settings_ID_Btn2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings_ID_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings_ID_Btn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Settings_ID_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Settings_ID_Btn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Settings_ID_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Settings_ID_Btn2, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Settings_Default_Volume = lv_obj_create(ui_Settings_List2);
lv_obj_remove_style_all(ui_Settings_Default_Volume);
lv_obj_set_width( ui_Settings_Default_Volume, 480);
lv_obj_set_height( ui_Settings_Default_Volume, 70);
lv_obj_set_x( ui_Settings_Default_Volume, 0 );
lv_obj_set_y( ui_Settings_Default_Volume, 100 );
lv_obj_set_align( ui_Settings_Default_Volume, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Default_Volume, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Default_Volume_Text = lv_label_create(ui_Settings_Default_Volume);
lv_obj_set_width( ui_Settings_Default_Volume_Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Default_Volume_Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Default_Volume_Text, 80 );
lv_obj_set_y( ui_Settings_Default_Volume_Text, 0 );
lv_obj_set_align( ui_Settings_Default_Volume_Text, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Settings_Default_Volume_Text,"默认音量");
lv_obj_set_style_text_color(ui_Settings_Default_Volume_Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Settings_Default_Volume_Text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Settings_Default_Volume_Text, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings_Default_Volume_Line = lv_obj_create(ui_Settings_Default_Volume);
lv_obj_set_width( ui_Settings_Default_Volume_Line, 450);
lv_obj_set_height( ui_Settings_Default_Volume_Line, 3);
lv_obj_set_x( ui_Settings_Default_Volume_Line, -1 );
lv_obj_set_y( ui_Settings_Default_Volume_Line, 30 );
lv_obj_set_align( ui_Settings_Default_Volume_Line, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Default_Volume_Line, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Default_Volume_Icon = lv_img_create(ui_Settings_Default_Volume);
lv_img_set_src(ui_Settings_Default_Volume_Icon, &ui_img_490182776);
lv_obj_set_width( ui_Settings_Default_Volume_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Default_Volume_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Default_Volume_Icon, -185 );
lv_obj_set_y( ui_Settings_Default_Volume_Icon, 0 );
lv_obj_set_align( ui_Settings_Default_Volume_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Default_Volume_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Default_Volume_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Default_Volume_Decora_Icon = lv_img_create(ui_Settings_Default_Volume);
lv_img_set_src(ui_Settings_Default_Volume_Decora_Icon, &ui_img_1830113796);
lv_obj_set_width( ui_Settings_Default_Volume_Decora_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Default_Volume_Decora_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Default_Volume_Decora_Icon, 210 );
lv_obj_set_y( ui_Settings_Default_Volume_Decora_Icon, 5 );
lv_obj_set_align( ui_Settings_Default_Volume_Decora_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Default_Volume_Decora_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Default_Volume_Decora_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Settings_Default_Volume_Decora_Icon,1800);

ui_Settings_Default_Volume_Btn = lv_btn_create(ui_Settings_Default_Volume);
lv_obj_set_width( ui_Settings_Default_Volume_Btn, 480);
lv_obj_set_height( ui_Settings_Default_Volume_Btn, 70);
lv_obj_set_align( ui_Settings_Default_Volume_Btn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Default_Volume_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Settings_Default_Volume_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings_Default_Volume_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings_Default_Volume_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Settings_Default_Volume_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Settings_Default_Volume_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Settings_Default_Volume_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Settings_Default_Volume_Btn, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Settings_Max_Volume = lv_obj_create(ui_Settings_List2);
lv_obj_remove_style_all(ui_Settings_Max_Volume);
lv_obj_set_width( ui_Settings_Max_Volume, 480);
lv_obj_set_height( ui_Settings_Max_Volume, 70);
lv_obj_set_x( ui_Settings_Max_Volume, 0 );
lv_obj_set_y( ui_Settings_Max_Volume, 170 );
lv_obj_set_align( ui_Settings_Max_Volume, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Max_Volume, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Max_Volume_Text2 = lv_label_create(ui_Settings_Max_Volume);
lv_obj_set_width( ui_Settings_Max_Volume_Text2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Max_Volume_Text2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Max_Volume_Text2, 80 );
lv_obj_set_y( ui_Settings_Max_Volume_Text2, 0 );
lv_obj_set_align( ui_Settings_Max_Volume_Text2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Settings_Max_Volume_Text2,"最大音量");
lv_obj_set_style_text_color(ui_Settings_Max_Volume_Text2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Settings_Max_Volume_Text2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Settings_Max_Volume_Text2, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings_Max_Volume_Line2 = lv_obj_create(ui_Settings_Max_Volume);
lv_obj_set_width( ui_Settings_Max_Volume_Line2, 450);
lv_obj_set_height( ui_Settings_Max_Volume_Line2, 3);
lv_obj_set_x( ui_Settings_Max_Volume_Line2, -1 );
lv_obj_set_y( ui_Settings_Max_Volume_Line2, 30 );
lv_obj_set_align( ui_Settings_Max_Volume_Line2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Max_Volume_Line2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Max_Volume_Icon2 = lv_img_create(ui_Settings_Max_Volume);
lv_img_set_src(ui_Settings_Max_Volume_Icon2, &ui_img_490182776);
lv_obj_set_width( ui_Settings_Max_Volume_Icon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Max_Volume_Icon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Max_Volume_Icon2, -185 );
lv_obj_set_y( ui_Settings_Max_Volume_Icon2, 0 );
lv_obj_set_align( ui_Settings_Max_Volume_Icon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Max_Volume_Icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Max_Volume_Icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Max_Volume_Decora_Icon2 = lv_img_create(ui_Settings_Max_Volume);
lv_img_set_src(ui_Settings_Max_Volume_Decora_Icon2, &ui_img_1830113796);
lv_obj_set_width( ui_Settings_Max_Volume_Decora_Icon2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Max_Volume_Decora_Icon2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Max_Volume_Decora_Icon2, 210 );
lv_obj_set_y( ui_Settings_Max_Volume_Decora_Icon2, 5 );
lv_obj_set_align( ui_Settings_Max_Volume_Decora_Icon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Max_Volume_Decora_Icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Max_Volume_Decora_Icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Settings_Max_Volume_Decora_Icon2,1800);

ui_Settings_Max_Volume_Btn2 = lv_btn_create(ui_Settings_Max_Volume);
lv_obj_set_width( ui_Settings_Max_Volume_Btn2, 480);
lv_obj_set_height( ui_Settings_Max_Volume_Btn2, 70);
lv_obj_set_align( ui_Settings_Max_Volume_Btn2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Max_Volume_Btn2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Settings_Max_Volume_Btn2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings_Max_Volume_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings_Max_Volume_Btn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Settings_Max_Volume_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Settings_Max_Volume_Btn2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Settings_Max_Volume_Btn2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Settings_Max_Volume_Btn2, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Default_Volume_Panel = lv_obj_create(ui_Settings_Window);
lv_obj_set_width( ui_Default_Volume_Panel, 300);
lv_obj_set_height( ui_Default_Volume_Panel, 180);
lv_obj_set_align( ui_Default_Volume_Panel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Default_Volume_Panel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Default_Volume_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Default_Volume_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Default_Volume_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Default_Volume_Text = lv_label_create(ui_Default_Volume_Panel);
lv_obj_set_width( ui_Default_Volume_Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Default_Volume_Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Default_Volume_Text, 0 );
lv_obj_set_y( ui_Default_Volume_Text, -54 );
lv_obj_set_align( ui_Default_Volume_Text, LV_ALIGN_CENTER );
lv_label_set_text(ui_Default_Volume_Text,"默认音量");
lv_obj_set_style_text_color(ui_Default_Volume_Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Default_Volume_Text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Default_Volume_Text, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Default_Volume_Text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Default_Volume_Text, &ui_font_LanTingFine22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Default_Volume_Verify_Btn = lv_obj_create(ui_Default_Volume_Panel);
lv_obj_set_width( ui_Default_Volume_Verify_Btn, 155);
lv_obj_set_height( ui_Default_Volume_Verify_Btn, 60);
lv_obj_set_x( ui_Default_Volume_Verify_Btn, -77 );
lv_obj_set_y( ui_Default_Volume_Verify_Btn, 68 );
lv_obj_set_align( ui_Default_Volume_Verify_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Default_Volume_Verify_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Default_Volume_Verify_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Default_Volume_Verify_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Default_Volume_Verify_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Default_Volume_Verify_Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Default_Volume_Verify_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Default_Volume_Verify_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Default_Volume_Verify_Btn, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Default_Volume_Verify_Btn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Default_Volume_Verify_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Default_Volume_Verify_Btn, 30, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Default_Volume_Verify_Btn_Text = lv_label_create(ui_Default_Volume_Verify_Btn);
lv_obj_set_width( ui_Default_Volume_Verify_Btn_Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Default_Volume_Verify_Btn_Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Default_Volume_Verify_Btn_Text, 4 );
lv_obj_set_y( ui_Default_Volume_Verify_Btn_Text, -2 );
lv_obj_set_align( ui_Default_Volume_Verify_Btn_Text, LV_ALIGN_CENTER );
lv_label_set_text(ui_Default_Volume_Verify_Btn_Text,"确认");
lv_obj_set_style_text_font(ui_Default_Volume_Verify_Btn_Text, &ui_font_LanTingFine22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Default_Volume_Cancel_Btn = lv_obj_create(ui_Default_Volume_Panel);
lv_obj_set_width( ui_Default_Volume_Cancel_Btn, 155);
lv_obj_set_height( ui_Default_Volume_Cancel_Btn, 60);
lv_obj_set_x( ui_Default_Volume_Cancel_Btn, 77 );
lv_obj_set_y( ui_Default_Volume_Cancel_Btn, 68 );
lv_obj_set_align( ui_Default_Volume_Cancel_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Default_Volume_Cancel_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Default_Volume_Cancel_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Default_Volume_Cancel_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Default_Volume_Cancel_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Default_Volume_Cancel_Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Default_Volume_Cancel_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Default_Volume_Cancel_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Default_Volume_Cancel_Btn, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Default_Volume_Cancel_Btn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Default_Volume_Cancel_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Default_Volume_Cancel_Btn, 30, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Default_Volume_Cancel_Text = lv_label_create(ui_Default_Volume_Cancel_Btn);
lv_obj_set_width( ui_Default_Volume_Cancel_Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Default_Volume_Cancel_Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Default_Volume_Cancel_Text, 4 );
lv_obj_set_y( ui_Default_Volume_Cancel_Text, -2 );
lv_obj_set_align( ui_Default_Volume_Cancel_Text, LV_ALIGN_CENTER );
lv_label_set_text(ui_Default_Volume_Cancel_Text,"取消");
lv_obj_set_style_text_font(ui_Default_Volume_Cancel_Text, &ui_font_LanTingFine22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Default_Volume_Value_Panel = lv_obj_create(ui_Default_Volume_Panel);
lv_obj_set_width( ui_Default_Volume_Value_Panel, 140);
lv_obj_set_height( ui_Default_Volume_Value_Panel, 39);
lv_obj_set_x( ui_Default_Volume_Value_Panel, 0 );
lv_obj_set_y( ui_Default_Volume_Value_Panel, -13 );
lv_obj_set_align( ui_Default_Volume_Value_Panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Default_Volume_Value_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Default_Volume_Value_Panel, lv_color_hex(0x959CFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Default_Volume_Value_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Default_Volume_Value_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Default_Volume_Value_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Default_Volume_Value = lv_label_create(ui_Default_Volume_Value_Panel);
lv_obj_set_width( ui_Default_Volume_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Default_Volume_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Default_Volume_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Default_Volume_Value,"5");
lv_obj_set_style_text_font(ui_Default_Volume_Value, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Default_Volume_Dec_Btn = lv_btn_create(ui_Default_Volume_Panel);
lv_obj_set_width( ui_Default_Volume_Dec_Btn, 60);
lv_obj_set_height( ui_Default_Volume_Dec_Btn, 60);
lv_obj_set_x( ui_Default_Volume_Dec_Btn, -107 );
lv_obj_set_y( ui_Default_Volume_Dec_Btn, -13 );
lv_obj_set_align( ui_Default_Volume_Dec_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Default_Volume_Dec_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Default_Volume_Dec_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Default_Volume_Dec_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Default_Volume_Dec_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Default_Volume_Dec_Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Default_Volume_Dec_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Default_Volume_Dec_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Default_Volume_Dec_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Default_Volume_Dec_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Default_Volume_Dec_Btn, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Default_Volume_Dec_Icon = lv_img_create(ui_Default_Volume_Dec_Btn);
lv_img_set_src(ui_Default_Volume_Dec_Icon, &ui_img_404002205);
lv_obj_set_width( ui_Default_Volume_Dec_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Default_Volume_Dec_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Default_Volume_Dec_Icon, 1 );
lv_obj_set_y( ui_Default_Volume_Dec_Icon, -1 );
lv_obj_set_align( ui_Default_Volume_Dec_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Default_Volume_Dec_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Default_Volume_Dec_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Default_Volume_Dec_Icon,300);

ui_Default_Volume_Add_Btn = lv_btn_create(ui_Default_Volume_Panel);
lv_obj_set_width( ui_Default_Volume_Add_Btn, 60);
lv_obj_set_height( ui_Default_Volume_Add_Btn, 60);
lv_obj_set_x( ui_Default_Volume_Add_Btn, 107 );
lv_obj_set_y( ui_Default_Volume_Add_Btn, -13 );
lv_obj_set_align( ui_Default_Volume_Add_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Default_Volume_Add_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Default_Volume_Add_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Default_Volume_Add_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Default_Volume_Add_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Default_Volume_Add_Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Default_Volume_Add_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Default_Volume_Add_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Default_Volume_Add_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Default_Volume_Add_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Default_Volume_Add_Btn, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Default_Volume_Add_Icon = lv_img_create(ui_Default_Volume_Add_Btn);
lv_img_set_src(ui_Default_Volume_Add_Icon, &ui_img_239308628);
lv_obj_set_width( ui_Default_Volume_Add_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Default_Volume_Add_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Default_Volume_Add_Icon, 1 );
lv_obj_set_y( ui_Default_Volume_Add_Icon, -1 );
lv_obj_set_align( ui_Default_Volume_Add_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Default_Volume_Add_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Default_Volume_Add_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Default_Volume_Add_Icon,300);

ui_Max_Volume_Panel = lv_obj_create(ui_Settings_Window);
lv_obj_set_width( ui_Max_Volume_Panel, 300);
lv_obj_set_height( ui_Max_Volume_Panel, 180);
lv_obj_set_align( ui_Max_Volume_Panel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Max_Volume_Panel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Max_Volume_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Max_Volume_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Max_Volume_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Max_Volume_Text = lv_label_create(ui_Max_Volume_Panel);
lv_obj_set_width( ui_Max_Volume_Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Max_Volume_Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Max_Volume_Text, 0 );
lv_obj_set_y( ui_Max_Volume_Text, -54 );
lv_obj_set_align( ui_Max_Volume_Text, LV_ALIGN_CENTER );
lv_label_set_text(ui_Max_Volume_Text,"最大音量");
lv_obj_set_style_text_color(ui_Max_Volume_Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Max_Volume_Text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Max_Volume_Text, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Max_Volume_Text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Max_Volume_Text, &ui_font_LanTingFine22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Max_Volume_Verify_Btn = lv_obj_create(ui_Max_Volume_Panel);
lv_obj_set_width( ui_Max_Volume_Verify_Btn, 155);
lv_obj_set_height( ui_Max_Volume_Verify_Btn, 60);
lv_obj_set_x( ui_Max_Volume_Verify_Btn, -77 );
lv_obj_set_y( ui_Max_Volume_Verify_Btn, 68 );
lv_obj_set_align( ui_Max_Volume_Verify_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Max_Volume_Verify_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Max_Volume_Verify_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Max_Volume_Verify_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Max_Volume_Verify_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Max_Volume_Verify_Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Max_Volume_Verify_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Max_Volume_Verify_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Max_Volume_Verify_Btn, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Max_Volume_Verify_Btn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Max_Volume_Verify_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Max_Volume_Verify_Btn, 30, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Max_Volume_Verify_Btn_Text = lv_label_create(ui_Max_Volume_Verify_Btn);
lv_obj_set_width( ui_Max_Volume_Verify_Btn_Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Max_Volume_Verify_Btn_Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Max_Volume_Verify_Btn_Text, 4 );
lv_obj_set_y( ui_Max_Volume_Verify_Btn_Text, -2 );
lv_obj_set_align( ui_Max_Volume_Verify_Btn_Text, LV_ALIGN_CENTER );
lv_label_set_text(ui_Max_Volume_Verify_Btn_Text,"确认");
lv_obj_set_style_text_font(ui_Max_Volume_Verify_Btn_Text, &ui_font_LanTingFine22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Max_Volume_Cancel_Btn = lv_obj_create(ui_Max_Volume_Panel);
lv_obj_set_width( ui_Max_Volume_Cancel_Btn, 155);
lv_obj_set_height( ui_Max_Volume_Cancel_Btn, 60);
lv_obj_set_x( ui_Max_Volume_Cancel_Btn, 77 );
lv_obj_set_y( ui_Max_Volume_Cancel_Btn, 68 );
lv_obj_set_align( ui_Max_Volume_Cancel_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Max_Volume_Cancel_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Max_Volume_Cancel_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Max_Volume_Cancel_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Max_Volume_Cancel_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Max_Volume_Cancel_Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Max_Volume_Cancel_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Max_Volume_Cancel_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Max_Volume_Cancel_Btn, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Max_Volume_Cancel_Btn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Max_Volume_Cancel_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Max_Volume_Cancel_Btn, 30, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Max_Volume_Cancel_Text = lv_label_create(ui_Max_Volume_Cancel_Btn);
lv_obj_set_width( ui_Max_Volume_Cancel_Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Max_Volume_Cancel_Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Max_Volume_Cancel_Text, 4 );
lv_obj_set_y( ui_Max_Volume_Cancel_Text, -2 );
lv_obj_set_align( ui_Max_Volume_Cancel_Text, LV_ALIGN_CENTER );
lv_label_set_text(ui_Max_Volume_Cancel_Text,"取消");
lv_obj_set_style_text_font(ui_Max_Volume_Cancel_Text, &ui_font_LanTingFine22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Max_Volume_Value_Panel = lv_obj_create(ui_Max_Volume_Panel);
lv_obj_set_width( ui_Max_Volume_Value_Panel, 140);
lv_obj_set_height( ui_Max_Volume_Value_Panel, 39);
lv_obj_set_x( ui_Max_Volume_Value_Panel, 0 );
lv_obj_set_y( ui_Max_Volume_Value_Panel, -13 );
lv_obj_set_align( ui_Max_Volume_Value_Panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Max_Volume_Value_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Max_Volume_Value_Panel, lv_color_hex(0x959CFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Max_Volume_Value_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Max_Volume_Value_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Max_Volume_Value_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Max_Volume_Value = lv_label_create(ui_Max_Volume_Value_Panel);
lv_obj_set_width( ui_Max_Volume_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Max_Volume_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Max_Volume_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Max_Volume_Value,"5");
lv_obj_set_style_text_font(ui_Max_Volume_Value, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Max_Volume_Dec_Btn = lv_btn_create(ui_Max_Volume_Panel);
lv_obj_set_width( ui_Max_Volume_Dec_Btn, 60);
lv_obj_set_height( ui_Max_Volume_Dec_Btn, 60);
lv_obj_set_x( ui_Max_Volume_Dec_Btn, -107 );
lv_obj_set_y( ui_Max_Volume_Dec_Btn, -13 );
lv_obj_set_align( ui_Max_Volume_Dec_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Max_Volume_Dec_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Max_Volume_Dec_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Max_Volume_Dec_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Max_Volume_Dec_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Max_Volume_Dec_Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Max_Volume_Dec_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Max_Volume_Dec_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Max_Volume_Dec_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Max_Volume_Dec_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Max_Volume_Dec_Btn, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Max_Volume_Dec_Icon = lv_img_create(ui_Max_Volume_Dec_Btn);
lv_img_set_src(ui_Max_Volume_Dec_Icon, &ui_img_404002205);
lv_obj_set_width( ui_Max_Volume_Dec_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Max_Volume_Dec_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Max_Volume_Dec_Icon, 1 );
lv_obj_set_y( ui_Max_Volume_Dec_Icon, -1 );
lv_obj_set_align( ui_Max_Volume_Dec_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Max_Volume_Dec_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Max_Volume_Dec_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Max_Volume_Dec_Icon,300);

ui_Max_Volume_Add_Btn = lv_btn_create(ui_Max_Volume_Panel);
lv_obj_set_width( ui_Max_Volume_Add_Btn, 60);
lv_obj_set_height( ui_Max_Volume_Add_Btn, 60);
lv_obj_set_x( ui_Max_Volume_Add_Btn, 107 );
lv_obj_set_y( ui_Max_Volume_Add_Btn, -13 );
lv_obj_set_align( ui_Max_Volume_Add_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Max_Volume_Add_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Max_Volume_Add_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Max_Volume_Add_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Max_Volume_Add_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Max_Volume_Add_Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Max_Volume_Add_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Max_Volume_Add_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Max_Volume_Add_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Max_Volume_Add_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Max_Volume_Add_Btn, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Max_Volume_Add_Icon = lv_img_create(ui_Max_Volume_Add_Btn);
lv_img_set_src(ui_Max_Volume_Add_Icon, &ui_img_239308628);
lv_obj_set_width( ui_Max_Volume_Add_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Max_Volume_Add_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Max_Volume_Add_Icon, 1 );
lv_obj_set_y( ui_Max_Volume_Add_Icon, -1 );
lv_obj_set_align( ui_Max_Volume_Add_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Max_Volume_Add_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Max_Volume_Add_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Max_Volume_Add_Icon,300);

ui_BackToMainWindowBtn8 = lv_imgbtn_create(ui_Settings_Window);
lv_imgbtn_set_src(ui_BackToMainWindowBtn8, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_348826415, NULL);
lv_imgbtn_set_src(ui_BackToMainWindowBtn8, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_348826415, NULL);
lv_obj_set_height( ui_BackToMainWindowBtn8, 50);
lv_obj_set_width( ui_BackToMainWindowBtn8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_BackToMainWindowBtn8, -212 );
lv_obj_set_y( ui_BackToMainWindowBtn8, -212 );
lv_obj_set_align( ui_BackToMainWindowBtn8, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_BackToMainWindowBtn8, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_BackToMainWindowBtn8, 100, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_add_event_cb(ui_Settings_Backlight_Btn2, ui_event_Settings_Backlight_Btn2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings_Bluetooth_Btn2, ui_event_Settings_Bluetooth_Btn2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings_Time_Btn2, ui_event_Settings_Time_Btn2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings_ID_Btn2, ui_event_Settings_ID_Btn2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings_Default_Volume_Btn, ui_event_Settings_Default_Volume_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings_Max_Volume_Btn2, ui_event_Settings_Max_Volume_Btn2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Default_Volume_Verify_Btn, ui_event_Default_Volume_Verify_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Default_Volume_Cancel_Btn, ui_event_Default_Volume_Cancel_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Default_Volume_Dec_Btn, ui_event_Default_Volume_Dec_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Default_Volume_Add_Btn, ui_event_Default_Volume_Add_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Max_Volume_Verify_Btn, ui_event_Max_Volume_Verify_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Max_Volume_Cancel_Btn, ui_event_Max_Volume_Cancel_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Max_Volume_Dec_Btn, ui_event_Max_Volume_Dec_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Max_Volume_Add_Btn, ui_event_Max_Volume_Add_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackToMainWindowBtn8, ui_event_BackToMainWindowBtn8, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings_Window, ui_event_Settings_Window, LV_EVENT_ALL, NULL);

}
