// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: settings

#include "../ui.h"

void ui_Backlight_Settings_screen_init(void)
{
ui_Backlight_Settings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Backlight_Settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Backlight_Settings, &ui_img_861711258, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Header_Main3 = lv_obj_create(ui_Backlight_Settings);
lv_obj_remove_style_all(ui_Header_Main3);
lv_obj_set_height( ui_Header_Main3, 30);
lv_obj_set_width( ui_Header_Main3, lv_pct(100));
lv_obj_set_x( ui_Header_Main3, 0 );
lv_obj_set_y( ui_Header_Main3, -225 );
lv_obj_set_align( ui_Header_Main3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Header_Main3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Header_Main_Text3 = lv_label_create(ui_Header_Main3);
lv_obj_set_width( ui_Header_Main_Text3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Main_Text3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Header_Main_Text3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Header_Main_Text3,"背光设置");
lv_obj_set_style_text_color(ui_Header_Main_Text3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Main_Text3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Header_Main_Text3, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Main_Time3 = lv_label_create(ui_Header_Main3);
lv_obj_set_width( ui_Header_Main_Time3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Main_Time3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Main_Time3, 300 );
lv_obj_set_y( ui_Header_Main_Time3, 0 );
lv_obj_set_align( ui_Header_Main_Time3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Header_Main_Time3,"");
lv_obj_set_style_text_color(ui_Header_Main_Time3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Main_Time3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Header_Main_Time3, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Main_Volume_Icon3 = lv_img_create(ui_Header_Main3);
lv_img_set_src(ui_Header_Main_Volume_Icon3, &ui_img_490182776);
lv_obj_set_width( ui_Header_Main_Volume_Icon3, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_Header_Main_Volume_Icon3, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_Header_Main_Volume_Icon3, 160 );
lv_obj_set_y( ui_Header_Main_Volume_Icon3, 0 );
lv_obj_set_align( ui_Header_Main_Volume_Icon3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Header_Main_Volume_Icon3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Header_Main_Volume_Icon3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Header_Main_Volume_Value3 = lv_label_create(ui_Header_Main3);
lv_obj_set_width( ui_Header_Main_Volume_Value3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Main_Volume_Value3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Main_Volume_Value3, 415 );
lv_obj_set_y( ui_Header_Main_Volume_Value3, 0 );
lv_obj_set_align( ui_Header_Main_Volume_Value3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Header_Main_Volume_Value3,"79");
lv_obj_set_style_text_color(ui_Header_Main_Volume_Value3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Main_Volume_Value3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Header_Main_Volume_Value3, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BackToMainWindow3 = lv_imgbtn_create(ui_Backlight_Settings);
lv_imgbtn_set_src(ui_BackToMainWindow3, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_348826415, NULL);
lv_imgbtn_set_src(ui_BackToMainWindow3, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_348826415, NULL);
lv_obj_set_height( ui_BackToMainWindow3, 50);
lv_obj_set_width( ui_BackToMainWindow3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_BackToMainWindow3, -212 );
lv_obj_set_y( ui_BackToMainWindow3, -212 );
lv_obj_set_align( ui_BackToMainWindow3, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_BackToMainWindow3, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_BackToMainWindow3, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Backlight_Settings_items = lv_obj_create(ui_Backlight_Settings);
lv_obj_remove_style_all(ui_Backlight_Settings_items);
lv_obj_set_width( ui_Backlight_Settings_items, 480);
lv_obj_set_height( ui_Backlight_Settings_items, 423);
lv_obj_set_x( ui_Backlight_Settings_items, 0 );
lv_obj_set_y( ui_Backlight_Settings_items, 26 );
lv_obj_set_align( ui_Backlight_Settings_items, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Backlight_Settings_items, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_Music_Item9 = lv_obj_create(ui_Backlight_Settings_items);
lv_obj_remove_style_all(ui_Music_Item9);
lv_obj_set_width( ui_Music_Item9, 480);
lv_obj_set_height( ui_Music_Item9, 70);
lv_obj_set_x( ui_Music_Item9, 0 );
lv_obj_set_y( ui_Music_Item9, -180 );
lv_obj_set_align( ui_Music_Item9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Music_Item9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Music_Name2 = lv_label_create(ui_Music_Item9);
lv_obj_set_width( ui_Music_Name2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Music_Name2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Music_Name2, 55 );
lv_obj_set_y( ui_Music_Name2, 0 );
lv_obj_set_align( ui_Music_Name2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Music_Name2,"背光亮度");
lv_obj_set_style_text_color(ui_Music_Name2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Music_Name2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Music_Name2, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Music_Item_Line2 = lv_obj_create(ui_Music_Item9);
lv_obj_set_width( ui_Music_Item_Line2, 450);
lv_obj_set_height( ui_Music_Item_Line2, 3);
lv_obj_set_x( ui_Music_Item_Line2, -1 );
lv_obj_set_y( ui_Music_Item_Line2, 30 );
lv_obj_set_align( ui_Music_Item_Line2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Music_Item_Line2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button1 = lv_btn_create(ui_Music_Item9);
lv_obj_set_width( ui_Button1, 480);
lv_obj_set_height( ui_Button1, 70);
lv_obj_set_align( ui_Button1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Button1, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Music_Item10 = lv_obj_create(ui_Backlight_Settings_items);
lv_obj_remove_style_all(ui_Music_Item10);
lv_obj_set_width( ui_Music_Item10, 480);
lv_obj_set_height( ui_Music_Item10, 70);
lv_obj_set_x( ui_Music_Item10, 0 );
lv_obj_set_y( ui_Music_Item10, -110 );
lv_obj_set_align( ui_Music_Item10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Music_Item10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Music_Name3 = lv_label_create(ui_Music_Item10);
lv_obj_set_width( ui_Music_Name3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Music_Name3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Music_Name3, 55 );
lv_obj_set_y( ui_Music_Name3, 0 );
lv_obj_set_align( ui_Music_Name3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Music_Name3,"背光时间");
lv_obj_set_style_text_color(ui_Music_Name3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Music_Name3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Music_Name3, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Music_Item_Line3 = lv_obj_create(ui_Music_Item10);
lv_obj_set_width( ui_Music_Item_Line3, 450);
lv_obj_set_height( ui_Music_Item_Line3, 3);
lv_obj_set_x( ui_Music_Item_Line3, -1 );
lv_obj_set_y( ui_Music_Item_Line3, 30 );
lv_obj_set_align( ui_Music_Item_Line3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Music_Item_Line3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button2 = lv_btn_create(ui_Music_Item10);
lv_obj_set_width( ui_Button2, 480);
lv_obj_set_height( ui_Button2, 70);
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Button2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Button2, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Backlight_Brightness_Panel = lv_obj_create(ui_Backlight_Settings);
lv_obj_set_width( ui_Backlight_Brightness_Panel, 300);
lv_obj_set_height( ui_Backlight_Brightness_Panel, 180);
lv_obj_set_align( ui_Backlight_Brightness_Panel, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Backlight_Brightness_Panel, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Backlight_Brightness_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Backlight_Brightness_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Backlight_Brightness_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Backlight_Brightness_Text = lv_label_create(ui_Backlight_Brightness_Panel);
lv_obj_set_width( ui_Backlight_Brightness_Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Backlight_Brightness_Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Backlight_Brightness_Text, 0 );
lv_obj_set_y( ui_Backlight_Brightness_Text, -54 );
lv_obj_set_align( ui_Backlight_Brightness_Text, LV_ALIGN_CENTER );
lv_label_set_text(ui_Backlight_Brightness_Text,"背光亮度");
lv_obj_set_style_text_color(ui_Backlight_Brightness_Text, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Backlight_Brightness_Text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_letter_space(ui_Backlight_Brightness_Text, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_line_space(ui_Backlight_Brightness_Text, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Backlight_Brightness_Text, &ui_font_LanTingFine22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Backlight_Verify_Btn = lv_obj_create(ui_Backlight_Brightness_Panel);
lv_obj_set_width( ui_Backlight_Verify_Btn, 155);
lv_obj_set_height( ui_Backlight_Verify_Btn, 60);
lv_obj_set_x( ui_Backlight_Verify_Btn, -77 );
lv_obj_set_y( ui_Backlight_Verify_Btn, 68 );
lv_obj_set_align( ui_Backlight_Verify_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Backlight_Verify_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Backlight_Verify_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Backlight_Verify_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Backlight_Verify_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Backlight_Verify_Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Backlight_Verify_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Backlight_Verify_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Backlight_Verify_Btn, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Backlight_Verify_Btn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Backlight_Verify_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Backlight_Verify_Btn, 30, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label4 = lv_label_create(ui_Backlight_Verify_Btn);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 4 );
lv_obj_set_y( ui_Label4, -2 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"确认");
lv_obj_set_style_text_font(ui_Label4, &ui_font_LanTingFine22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Backlight_Cancel_Btn = lv_obj_create(ui_Backlight_Brightness_Panel);
lv_obj_set_width( ui_Backlight_Cancel_Btn, 155);
lv_obj_set_height( ui_Backlight_Cancel_Btn, 60);
lv_obj_set_x( ui_Backlight_Cancel_Btn, 77 );
lv_obj_set_y( ui_Backlight_Cancel_Btn, 68 );
lv_obj_set_align( ui_Backlight_Cancel_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Backlight_Cancel_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Backlight_Cancel_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Backlight_Cancel_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Backlight_Cancel_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Backlight_Cancel_Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Backlight_Cancel_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Backlight_Cancel_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Backlight_Cancel_Btn, 100, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Backlight_Cancel_Btn, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Backlight_Cancel_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Backlight_Cancel_Btn, 30, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Label1 = lv_label_create(ui_Backlight_Cancel_Btn);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 4 );
lv_obj_set_y( ui_Label1, -2 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"取消");
lv_obj_set_style_text_font(ui_Label1, &ui_font_LanTingFine22, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Backlight_Brightness_Value_Panel = lv_obj_create(ui_Backlight_Brightness_Panel);
lv_obj_set_width( ui_Backlight_Brightness_Value_Panel, 140);
lv_obj_set_height( ui_Backlight_Brightness_Value_Panel, 39);
lv_obj_set_x( ui_Backlight_Brightness_Value_Panel, 0 );
lv_obj_set_y( ui_Backlight_Brightness_Value_Panel, -13 );
lv_obj_set_align( ui_Backlight_Brightness_Value_Panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Backlight_Brightness_Value_Panel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Backlight_Brightness_Value_Panel, lv_color_hex(0x959CFA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Backlight_Brightness_Value_Panel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Backlight_Brightness_Value_Panel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Backlight_Brightness_Value_Panel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Backlight_Brightness_Value = lv_label_create(ui_Backlight_Brightness_Value_Panel);
lv_obj_set_width( ui_Backlight_Brightness_Value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Backlight_Brightness_Value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Backlight_Brightness_Value, LV_ALIGN_CENTER );
lv_label_set_text(ui_Backlight_Brightness_Value,"5");
lv_obj_set_style_text_font(ui_Backlight_Brightness_Value, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Backlight_Dec_Btn = lv_btn_create(ui_Backlight_Brightness_Panel);
lv_obj_set_width( ui_Backlight_Dec_Btn, 60);
lv_obj_set_height( ui_Backlight_Dec_Btn, 60);
lv_obj_set_x( ui_Backlight_Dec_Btn, -107 );
lv_obj_set_y( ui_Backlight_Dec_Btn, -13 );
lv_obj_set_align( ui_Backlight_Dec_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Backlight_Dec_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Backlight_Dec_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Backlight_Dec_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Backlight_Dec_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Backlight_Dec_Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Backlight_Dec_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Backlight_Dec_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Backlight_Dec_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Backlight_Dec_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Backlight_Dec_Btn, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Backlight_Dec_Icon = lv_img_create(ui_Backlight_Dec_Btn);
lv_img_set_src(ui_Backlight_Dec_Icon, &ui_img_404002205);
lv_obj_set_width( ui_Backlight_Dec_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Backlight_Dec_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Backlight_Dec_Icon, 1 );
lv_obj_set_y( ui_Backlight_Dec_Icon, -1 );
lv_obj_set_align( ui_Backlight_Dec_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Backlight_Dec_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Backlight_Dec_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Backlight_Dec_Icon,300);

ui_Backlight_Add_Btn = lv_btn_create(ui_Backlight_Brightness_Panel);
lv_obj_set_width( ui_Backlight_Add_Btn, 60);
lv_obj_set_height( ui_Backlight_Add_Btn, 60);
lv_obj_set_x( ui_Backlight_Add_Btn, 107 );
lv_obj_set_y( ui_Backlight_Add_Btn, -13 );
lv_obj_set_align( ui_Backlight_Add_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Backlight_Add_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Backlight_Add_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Backlight_Add_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Backlight_Add_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Backlight_Add_Btn, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Backlight_Add_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Backlight_Add_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Backlight_Add_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Backlight_Add_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Backlight_Add_Btn, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Backlight_Add_Icon = lv_img_create(ui_Backlight_Add_Btn);
lv_img_set_src(ui_Backlight_Add_Icon, &ui_img_239308628);
lv_obj_set_width( ui_Backlight_Add_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Backlight_Add_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Backlight_Add_Icon, 1 );
lv_obj_set_y( ui_Backlight_Add_Icon, -1 );
lv_obj_set_align( ui_Backlight_Add_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Backlight_Add_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Backlight_Add_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Backlight_Add_Icon,300);

lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Backlight_Verify_Btn, ui_event_Backlight_Verify_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Backlight_Cancel_Btn, ui_event_Backlight_Cancel_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Backlight_Dec_Btn, ui_event_Backlight_Dec_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Backlight_Add_Btn, ui_event_Backlight_Add_Btn, LV_EVENT_ALL, NULL);

}
