// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: settings

#include "../ui.h"

void ui_Settings_screen_init(void)
{
ui_Settings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Settings, &ui_img_861711258, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Header_Main2 = lv_obj_create(ui_Settings);
lv_obj_remove_style_all(ui_Header_Main2);
lv_obj_set_height( ui_Header_Main2, 30);
lv_obj_set_width( ui_Header_Main2, lv_pct(100));
lv_obj_set_x( ui_Header_Main2, 0 );
lv_obj_set_y( ui_Header_Main2, -225 );
lv_obj_set_align( ui_Header_Main2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Header_Main2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Header_Main_Text2 = lv_label_create(ui_Header_Main2);
lv_obj_set_width( ui_Header_Main_Text2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Main_Text2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Header_Main_Text2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Header_Main_Text2,"设置");
lv_obj_set_style_text_color(ui_Header_Main_Text2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Main_Text2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Header_Main_Text2, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Main_Time2 = lv_label_create(ui_Header_Main2);
lv_obj_set_width( ui_Header_Main_Time2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Main_Time2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Main_Time2, 300 );
lv_obj_set_y( ui_Header_Main_Time2, 0 );
lv_obj_set_align( ui_Header_Main_Time2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Header_Main_Time2,"");
lv_obj_set_style_text_color(ui_Header_Main_Time2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Main_Time2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Header_Main_Time2, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Main_Volume_Icon2 = lv_img_create(ui_Header_Main2);
lv_img_set_src(ui_Header_Main_Volume_Icon2, &ui_img_490182776);
lv_obj_set_width( ui_Header_Main_Volume_Icon2, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_Header_Main_Volume_Icon2, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_Header_Main_Volume_Icon2, 160 );
lv_obj_set_y( ui_Header_Main_Volume_Icon2, 0 );
lv_obj_set_align( ui_Header_Main_Volume_Icon2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Header_Main_Volume_Icon2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Header_Main_Volume_Icon2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Header_Main_Volume_Value2 = lv_label_create(ui_Header_Main2);
lv_obj_set_width( ui_Header_Main_Volume_Value2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Main_Volume_Value2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Main_Volume_Value2, 415 );
lv_obj_set_y( ui_Header_Main_Volume_Value2, 0 );
lv_obj_set_align( ui_Header_Main_Volume_Value2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Header_Main_Volume_Value2,"79");
lv_obj_set_style_text_color(ui_Header_Main_Volume_Value2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Main_Volume_Value2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Header_Main_Volume_Value2, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings_List = lv_obj_create(ui_Settings);
lv_obj_remove_style_all(ui_Settings_List);
lv_obj_set_width( ui_Settings_List, 480);
lv_obj_set_height( ui_Settings_List, 423);
lv_obj_set_x( ui_Settings_List, 0 );
lv_obj_set_y( ui_Settings_List, 26 );
lv_obj_set_align( ui_Settings_List, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_List, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_Settings_Backlight = lv_obj_create(ui_Settings_List);
lv_obj_remove_style_all(ui_Settings_Backlight);
lv_obj_set_width( ui_Settings_Backlight, 480);
lv_obj_set_height( ui_Settings_Backlight, 70);
lv_obj_set_x( ui_Settings_Backlight, 0 );
lv_obj_set_y( ui_Settings_Backlight, -180 );
lv_obj_set_align( ui_Settings_Backlight, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Backlight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Backlight_Text = lv_label_create(ui_Settings_Backlight);
lv_obj_set_width( ui_Settings_Backlight_Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Backlight_Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Backlight_Text, 80 );
lv_obj_set_y( ui_Settings_Backlight_Text, 0 );
lv_obj_set_align( ui_Settings_Backlight_Text, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Settings_Backlight_Text,"背光设置");
lv_obj_set_style_text_color(ui_Settings_Backlight_Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Settings_Backlight_Text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Settings_Backlight_Text, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings_Backlight_Line = lv_obj_create(ui_Settings_Backlight);
lv_obj_set_width( ui_Settings_Backlight_Line, 450);
lv_obj_set_height( ui_Settings_Backlight_Line, 3);
lv_obj_set_x( ui_Settings_Backlight_Line, -1 );
lv_obj_set_y( ui_Settings_Backlight_Line, 30 );
lv_obj_set_align( ui_Settings_Backlight_Line, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Backlight_Line, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Backlight_Icon = lv_img_create(ui_Settings_Backlight);
lv_img_set_src(ui_Settings_Backlight_Icon, &ui_img_149594991);
lv_obj_set_width( ui_Settings_Backlight_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Backlight_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Backlight_Icon, -185 );
lv_obj_set_y( ui_Settings_Backlight_Icon, 0 );
lv_obj_set_align( ui_Settings_Backlight_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Backlight_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Backlight_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Backlight_Decora_Icon = lv_img_create(ui_Settings_Backlight);
lv_img_set_src(ui_Settings_Backlight_Decora_Icon, &ui_img_1830113796);
lv_obj_set_width( ui_Settings_Backlight_Decora_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Backlight_Decora_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Backlight_Decora_Icon, 210 );
lv_obj_set_y( ui_Settings_Backlight_Decora_Icon, 5 );
lv_obj_set_align( ui_Settings_Backlight_Decora_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Backlight_Decora_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Backlight_Decora_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Settings_Backlight_Decora_Icon,1800);

ui_Settings_Backlight_Btn = lv_btn_create(ui_Settings_Backlight);
lv_obj_set_width( ui_Settings_Backlight_Btn, 480);
lv_obj_set_height( ui_Settings_Backlight_Btn, 70);
lv_obj_set_align( ui_Settings_Backlight_Btn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Backlight_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Settings_Backlight_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings_Backlight_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings_Backlight_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Settings_Backlight_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Settings_Backlight_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Settings_Backlight_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Settings_Backlight_Btn, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Settings_Bluetooth = lv_obj_create(ui_Settings_List);
lv_obj_remove_style_all(ui_Settings_Bluetooth);
lv_obj_set_width( ui_Settings_Bluetooth, 480);
lv_obj_set_height( ui_Settings_Bluetooth, 70);
lv_obj_set_x( ui_Settings_Bluetooth, 0 );
lv_obj_set_y( ui_Settings_Bluetooth, -110 );
lv_obj_set_align( ui_Settings_Bluetooth, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Bluetooth, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Bluetooth_Text = lv_label_create(ui_Settings_Bluetooth);
lv_obj_set_width( ui_Settings_Bluetooth_Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Bluetooth_Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Bluetooth_Text, 80 );
lv_obj_set_y( ui_Settings_Bluetooth_Text, 0 );
lv_obj_set_align( ui_Settings_Bluetooth_Text, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Settings_Bluetooth_Text,"蓝牙设置");
lv_obj_set_style_text_color(ui_Settings_Bluetooth_Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Settings_Bluetooth_Text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Settings_Bluetooth_Text, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings_Bluetooth_Line = lv_obj_create(ui_Settings_Bluetooth);
lv_obj_set_width( ui_Settings_Bluetooth_Line, 450);
lv_obj_set_height( ui_Settings_Bluetooth_Line, 3);
lv_obj_set_x( ui_Settings_Bluetooth_Line, -1 );
lv_obj_set_y( ui_Settings_Bluetooth_Line, 30 );
lv_obj_set_align( ui_Settings_Bluetooth_Line, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Bluetooth_Line, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Bluetooth_Icon = lv_img_create(ui_Settings_Bluetooth);
lv_img_set_src(ui_Settings_Bluetooth_Icon, &ui_img_1711952528);
lv_obj_set_width( ui_Settings_Bluetooth_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Bluetooth_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Bluetooth_Icon, -185 );
lv_obj_set_y( ui_Settings_Bluetooth_Icon, 0 );
lv_obj_set_align( ui_Settings_Bluetooth_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Bluetooth_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Bluetooth_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Bluetooth_Decora_Icon = lv_img_create(ui_Settings_Bluetooth);
lv_img_set_src(ui_Settings_Bluetooth_Decora_Icon, &ui_img_1830113796);
lv_obj_set_width( ui_Settings_Bluetooth_Decora_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Bluetooth_Decora_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Bluetooth_Decora_Icon, 210 );
lv_obj_set_y( ui_Settings_Bluetooth_Decora_Icon, 5 );
lv_obj_set_align( ui_Settings_Bluetooth_Decora_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Bluetooth_Decora_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Bluetooth_Decora_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Settings_Bluetooth_Decora_Icon,1800);

ui_Settings_Bluetooth_Btn = lv_btn_create(ui_Settings_Bluetooth);
lv_obj_set_width( ui_Settings_Bluetooth_Btn, 480);
lv_obj_set_height( ui_Settings_Bluetooth_Btn, 70);
lv_obj_set_align( ui_Settings_Bluetooth_Btn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Bluetooth_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Settings_Bluetooth_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings_Bluetooth_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings_Bluetooth_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Settings_Bluetooth_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Settings_Bluetooth_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Settings_Bluetooth_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Settings_Bluetooth_Btn, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Settings_Time = lv_obj_create(ui_Settings_List);
lv_obj_remove_style_all(ui_Settings_Time);
lv_obj_set_width( ui_Settings_Time, 480);
lv_obj_set_height( ui_Settings_Time, 70);
lv_obj_set_x( ui_Settings_Time, 0 );
lv_obj_set_y( ui_Settings_Time, -40 );
lv_obj_set_align( ui_Settings_Time, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Time, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Time_Text = lv_label_create(ui_Settings_Time);
lv_obj_set_width( ui_Settings_Time_Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Time_Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Time_Text, 80 );
lv_obj_set_y( ui_Settings_Time_Text, 0 );
lv_obj_set_align( ui_Settings_Time_Text, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Settings_Time_Text,"时间设置");
lv_obj_set_style_text_color(ui_Settings_Time_Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Settings_Time_Text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Settings_Time_Text, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings_Time_Line = lv_obj_create(ui_Settings_Time);
lv_obj_set_width( ui_Settings_Time_Line, 450);
lv_obj_set_height( ui_Settings_Time_Line, 3);
lv_obj_set_x( ui_Settings_Time_Line, -1 );
lv_obj_set_y( ui_Settings_Time_Line, 30 );
lv_obj_set_align( ui_Settings_Time_Line, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Settings_Time_Line, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Time_Icon = lv_img_create(ui_Settings_Time);
lv_img_set_src(ui_Settings_Time_Icon, &ui_img_1422805608);
lv_obj_set_width( ui_Settings_Time_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Time_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Time_Icon, -185 );
lv_obj_set_y( ui_Settings_Time_Icon, 0 );
lv_obj_set_align( ui_Settings_Time_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Time_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Time_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Settings_Time_Decora_Icon = lv_img_create(ui_Settings_Time);
lv_img_set_src(ui_Settings_Time_Decora_Icon, &ui_img_1830113796);
lv_obj_set_width( ui_Settings_Time_Decora_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings_Time_Decora_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings_Time_Decora_Icon, 210 );
lv_obj_set_y( ui_Settings_Time_Decora_Icon, 5 );
lv_obj_set_align( ui_Settings_Time_Decora_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Time_Decora_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Settings_Time_Decora_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_Settings_Time_Decora_Icon,1800);

ui_Settings_Time_Btn = lv_btn_create(ui_Settings_Time);
lv_obj_set_width( ui_Settings_Time_Btn, 480);
lv_obj_set_height( ui_Settings_Time_Btn, 70);
lv_obj_set_align( ui_Settings_Time_Btn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Settings_Time_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Settings_Time_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Settings_Time_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings_Time_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Settings_Time_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Settings_Time_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Settings_Time_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Settings_Time_Btn, 100, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Music_Item4 = ui_Music_Item1_create(ui_Settings_List);
lv_obj_set_x( ui_Music_Item4, 0 );
lv_obj_set_y( ui_Music_Item4, 30 );





ui_Music_Item5 = ui_Music_Item1_create(ui_Settings_List);
lv_obj_set_x( ui_Music_Item5, 0 );
lv_obj_set_y( ui_Music_Item5, 100 );





ui_Music_Item6 = ui_Music_Item1_create(ui_Settings_List);
lv_obj_set_x( ui_Music_Item6, 0 );
lv_obj_set_y( ui_Music_Item6, 170 );





ui_Music_Item7 = ui_Music_Item1_create(ui_Settings_List);
lv_obj_set_x( ui_Music_Item7, 0 );
lv_obj_set_y( ui_Music_Item7, 240 );





ui_BackToMainWindow2 = lv_imgbtn_create(ui_Settings);
lv_imgbtn_set_src(ui_BackToMainWindow2, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_348826415, NULL);
lv_imgbtn_set_src(ui_BackToMainWindow2, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_348826415, NULL);
lv_obj_set_height( ui_BackToMainWindow2, 50);
lv_obj_set_width( ui_BackToMainWindow2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_BackToMainWindow2, -212 );
lv_obj_set_y( ui_BackToMainWindow2, -212 );
lv_obj_set_align( ui_BackToMainWindow2, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_BackToMainWindow2, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_BackToMainWindow2, 100, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_add_event_cb(ui_Settings_Backlight_Btn, ui_event_Settings_Backlight_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings_Bluetooth_Btn, ui_event_Settings_Bluetooth_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings_Time_Btn, ui_event_Settings_Time_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Settings, ui_event_Settings, LV_EVENT_ALL, NULL);

}
