// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: settings

#include "../ui.h"

void ui_Time_Settings_screen_init(void)
{
ui_Time_Settings = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Time_Settings, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_img_src( ui_Time_Settings, &ui_img_861711258, LV_PART_MAIN | LV_STATE_DEFAULT );

ui_Header_Main5 = lv_obj_create(ui_Time_Settings);
lv_obj_remove_style_all(ui_Header_Main5);
lv_obj_set_height( ui_Header_Main5, 30);
lv_obj_set_width( ui_Header_Main5, lv_pct(100));
lv_obj_set_x( ui_Header_Main5, 0 );
lv_obj_set_y( ui_Header_Main5, -225 );
lv_obj_set_align( ui_Header_Main5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Header_Main5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Header_Main_Text5 = lv_label_create(ui_Header_Main5);
lv_obj_set_width( ui_Header_Main_Text5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Main_Text5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Header_Main_Text5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Header_Main_Text5,"时间设置");
lv_obj_set_style_text_color(ui_Header_Main_Text5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Main_Text5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Header_Main_Text5, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Main_Time5 = lv_label_create(ui_Header_Main5);
lv_obj_set_width( ui_Header_Main_Time5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Main_Time5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Main_Time5, 300 );
lv_obj_set_y( ui_Header_Main_Time5, 0 );
lv_obj_set_align( ui_Header_Main_Time5, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Header_Main_Time5,"");
lv_obj_set_style_text_color(ui_Header_Main_Time5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Main_Time5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Header_Main_Time5, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Header_Main_Volume_Icon5 = lv_img_create(ui_Header_Main5);
lv_img_set_src(ui_Header_Main_Volume_Icon5, &ui_img_490182776);
lv_obj_set_width( ui_Header_Main_Volume_Icon5, LV_SIZE_CONTENT);  /// 22
lv_obj_set_height( ui_Header_Main_Volume_Icon5, LV_SIZE_CONTENT);   /// 20
lv_obj_set_x( ui_Header_Main_Volume_Icon5, 160 );
lv_obj_set_y( ui_Header_Main_Volume_Icon5, 0 );
lv_obj_set_align( ui_Header_Main_Volume_Icon5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Header_Main_Volume_Icon5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Header_Main_Volume_Icon5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Header_Main_Volume_Value5 = lv_label_create(ui_Header_Main5);
lv_obj_set_width( ui_Header_Main_Volume_Value5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Header_Main_Volume_Value5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Header_Main_Volume_Value5, 415 );
lv_obj_set_y( ui_Header_Main_Volume_Value5, 0 );
lv_obj_set_align( ui_Header_Main_Volume_Value5, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Header_Main_Volume_Value5,"79");
lv_obj_set_style_text_color(ui_Header_Main_Volume_Value5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Header_Main_Volume_Value5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Header_Main_Volume_Value5, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Time_Setting_Panel = lv_obj_create(ui_Time_Settings);
lv_obj_remove_style_all(ui_Time_Setting_Panel);
lv_obj_set_width( ui_Time_Setting_Panel, 480);
lv_obj_set_height( ui_Time_Setting_Panel, 70);
lv_obj_set_x( ui_Time_Setting_Panel, 0 );
lv_obj_set_y( ui_Time_Setting_Panel, -160 );
lv_obj_set_align( ui_Time_Setting_Panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Time_Setting_Panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Time_Setting_Text = lv_label_create(ui_Time_Setting_Panel);
lv_obj_set_width( ui_Time_Setting_Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Time_Setting_Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Time_Setting_Text, 27 );
lv_obj_set_y( ui_Time_Setting_Text, 4 );
lv_obj_set_align( ui_Time_Setting_Text, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Time_Setting_Text,"时间:                       :");
lv_obj_set_style_text_color(ui_Time_Setting_Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Time_Setting_Text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Time_Setting_Text, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Time_Setting_Line = lv_obj_create(ui_Time_Setting_Panel);
lv_obj_set_width( ui_Time_Setting_Line, 450);
lv_obj_set_height( ui_Time_Setting_Line, 3);
lv_obj_set_x( ui_Time_Setting_Line, -1 );
lv_obj_set_y( ui_Time_Setting_Line, 30 );
lv_obj_set_align( ui_Time_Setting_Line, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Time_Setting_Line, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Time_Setting_Hour = lv_textarea_create(ui_Time_Setting_Panel);
lv_obj_set_width( ui_Time_Setting_Hour, 76);
lv_obj_set_height( ui_Time_Setting_Hour, LV_SIZE_CONTENT);   /// 43
lv_obj_set_x( ui_Time_Setting_Hour, -100 );
lv_obj_set_y( ui_Time_Setting_Hour, 0 );
lv_obj_set_align( ui_Time_Setting_Hour, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_Time_Setting_Hour,2);
lv_textarea_set_text(ui_Time_Setting_Hour,"11");
lv_textarea_set_placeholder_text(ui_Time_Setting_Hour,"11");
lv_textarea_set_one_line(ui_Time_Setting_Hour,true);
lv_obj_clear_flag( ui_Time_Setting_Hour, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_Time_Setting_Hour, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Time_Setting_Min = lv_textarea_create(ui_Time_Setting_Panel);
lv_obj_set_width( ui_Time_Setting_Min, 76);
lv_obj_set_height( ui_Time_Setting_Min, LV_SIZE_CONTENT);   /// 43
lv_obj_set_x( ui_Time_Setting_Min, -5 );
lv_obj_set_y( ui_Time_Setting_Min, 0 );
lv_obj_set_align( ui_Time_Setting_Min, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_Time_Setting_Min,2);
lv_textarea_set_text(ui_Time_Setting_Min,"42");
lv_textarea_set_placeholder_text(ui_Time_Setting_Min,"42");
lv_textarea_set_one_line(ui_Time_Setting_Min,true);
lv_obj_clear_flag( ui_Time_Setting_Min, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_Time_Setting_Min, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Time_Setting_Enter_Btn = lv_btn_create(ui_Time_Setting_Panel);
lv_obj_set_width( ui_Time_Setting_Enter_Btn, 60);
lv_obj_set_height( ui_Time_Setting_Enter_Btn, 60);
lv_obj_set_x( ui_Time_Setting_Enter_Btn, 190 );
lv_obj_set_y( ui_Time_Setting_Enter_Btn, -3 );
lv_obj_set_align( ui_Time_Setting_Enter_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Time_Setting_Enter_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Time_Setting_Enter_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Time_Setting_Enter_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Time_Setting_Enter_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_shadow_color(ui_Time_Setting_Enter_Btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Time_Setting_Enter_Btn, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Time_Setting_Enter_Btn, lv_color_hex(0x4893EF), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_Time_Setting_Enter_Btn, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Time_Setting_Enter_Icon = lv_img_create(ui_Time_Setting_Enter_Btn);
lv_img_set_src(ui_Time_Setting_Enter_Icon, &ui_img_1260392355);
lv_obj_set_width( ui_Time_Setting_Enter_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Time_Setting_Enter_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Time_Setting_Enter_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Time_Setting_Enter_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Time_Setting_Enter_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Date_Setting_Panel = lv_obj_create(ui_Time_Settings);
lv_obj_remove_style_all(ui_Date_Setting_Panel);
lv_obj_set_width( ui_Date_Setting_Panel, 480);
lv_obj_set_height( ui_Date_Setting_Panel, 70);
lv_obj_set_x( ui_Date_Setting_Panel, 0 );
lv_obj_set_y( ui_Date_Setting_Panel, -76 );
lv_obj_set_align( ui_Date_Setting_Panel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Date_Setting_Panel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Date_Settings_Text = lv_label_create(ui_Date_Setting_Panel);
lv_obj_set_width( ui_Date_Settings_Text, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Date_Settings_Text, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Date_Settings_Text, 27 );
lv_obj_set_y( ui_Date_Settings_Text, 0 );
lv_obj_set_align( ui_Date_Settings_Text, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Date_Settings_Text,"日期:                      -                 -");
lv_obj_set_style_text_color(ui_Date_Settings_Text, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Date_Settings_Text, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Date_Settings_Text, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Date_Setting_Line = lv_obj_create(ui_Date_Setting_Panel);
lv_obj_set_width( ui_Date_Setting_Line, 450);
lv_obj_set_height( ui_Date_Setting_Line, 3);
lv_obj_set_x( ui_Date_Setting_Line, -1 );
lv_obj_set_y( ui_Date_Setting_Line, 30 );
lv_obj_set_align( ui_Date_Setting_Line, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Date_Setting_Line, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Date_Setting_Year = lv_textarea_create(ui_Date_Setting_Panel);
lv_obj_set_width( ui_Date_Setting_Year, 76);
lv_obj_set_height( ui_Date_Setting_Year, LV_SIZE_CONTENT);   /// 43
lv_obj_set_x( ui_Date_Setting_Year, -100 );
lv_obj_set_y( ui_Date_Setting_Year, 0 );
lv_obj_set_align( ui_Date_Setting_Year, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_Date_Setting_Year,4);
lv_textarea_set_text(ui_Date_Setting_Year,"2022");
lv_textarea_set_placeholder_text(ui_Date_Setting_Year,"2022");
lv_textarea_set_one_line(ui_Date_Setting_Year,true);
lv_obj_clear_flag( ui_Date_Setting_Year, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_Date_Setting_Year, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Date_Setting_Month = lv_textarea_create(ui_Date_Setting_Panel);
lv_obj_set_width( ui_Date_Setting_Month, 76);
lv_obj_set_height( ui_Date_Setting_Month, LV_SIZE_CONTENT);   /// 43
lv_obj_set_x( ui_Date_Setting_Month, -5 );
lv_obj_set_y( ui_Date_Setting_Month, 0 );
lv_obj_set_align( ui_Date_Setting_Month, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_Date_Setting_Month,2);
lv_textarea_set_text(ui_Date_Setting_Month,"04");
lv_textarea_set_placeholder_text(ui_Date_Setting_Month,"04");
lv_textarea_set_one_line(ui_Date_Setting_Month,true);
lv_obj_clear_flag( ui_Date_Setting_Month, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_Date_Setting_Month, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Date_Setting_Day = lv_textarea_create(ui_Date_Setting_Panel);
lv_obj_set_width( ui_Date_Setting_Day, 76);
lv_obj_set_height( ui_Date_Setting_Day, LV_SIZE_CONTENT);   /// 43
lv_obj_set_x( ui_Date_Setting_Day, 90 );
lv_obj_set_y( ui_Date_Setting_Day, 0 );
lv_obj_set_align( ui_Date_Setting_Day, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_Date_Setting_Day,2);
lv_textarea_set_text(ui_Date_Setting_Day,"13");
lv_textarea_set_placeholder_text(ui_Date_Setting_Day,"13");
lv_textarea_set_one_line(ui_Date_Setting_Day,true);
lv_obj_clear_flag( ui_Date_Setting_Day, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_text_font(ui_Date_Setting_Day, &ui_font_LanTing18, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_Date_Setting_Enter_Btn = lv_btn_create(ui_Date_Setting_Panel);
lv_obj_set_width( ui_Date_Setting_Enter_Btn, 60);
lv_obj_set_height( ui_Date_Setting_Enter_Btn, 60);
lv_obj_set_x( ui_Date_Setting_Enter_Btn, 190 );
lv_obj_set_y( ui_Date_Setting_Enter_Btn, -3 );
lv_obj_set_align( ui_Date_Setting_Enter_Btn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Date_Setting_Enter_Btn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Date_Setting_Enter_Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_Date_Setting_Enter_Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Date_Setting_Enter_Btn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Date_Setting_Enter_Icon = lv_img_create(ui_Date_Setting_Enter_Btn);
lv_img_set_src(ui_Date_Setting_Enter_Icon, &ui_img_1260392355);
lv_obj_set_width( ui_Date_Setting_Enter_Icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Date_Setting_Enter_Icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Date_Setting_Enter_Icon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Date_Setting_Enter_Icon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Date_Setting_Enter_Icon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Date_Time_Keyboard = lv_keyboard_create(ui_Time_Settings);
lv_keyboard_set_mode(ui_Date_Time_Keyboard,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Date_Time_Keyboard, 480);
lv_obj_set_height( ui_Date_Time_Keyboard, 230);
lv_obj_set_x( ui_Date_Time_Keyboard, 0 );
lv_obj_set_y( ui_Date_Time_Keyboard, 120 );
lv_obj_set_align( ui_Date_Time_Keyboard, LV_ALIGN_CENTER );

ui_BackToMainWindow5 = lv_imgbtn_create(ui_Time_Settings);
lv_imgbtn_set_src(ui_BackToMainWindow5, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_348826415, NULL);
lv_imgbtn_set_src(ui_BackToMainWindow5, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_348826415, NULL);
lv_obj_set_height( ui_BackToMainWindow5, 50);
lv_obj_set_width( ui_BackToMainWindow5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_x( ui_BackToMainWindow5, -212 );
lv_obj_set_y( ui_BackToMainWindow5, -212 );
lv_obj_set_align( ui_BackToMainWindow5, LV_ALIGN_CENTER );
lv_obj_set_style_img_recolor(ui_BackToMainWindow5, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_PRESSED);
lv_obj_set_style_img_recolor_opa(ui_BackToMainWindow5, 100, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_add_event_cb(ui_Time_Setting_Hour, ui_event_Time_Setting_Hour, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Time_Setting_Min, ui_event_Time_Setting_Min, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Time_Setting_Enter_Btn, ui_event_Time_Setting_Enter_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Date_Setting_Year, ui_event_Date_Setting_Year, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Date_Setting_Month, ui_event_Date_Setting_Month, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Date_Setting_Day, ui_event_Date_Setting_Day, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Date_Setting_Enter_Btn, ui_event_Date_Setting_Enter_Btn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BackToMainWindow5, ui_event_BackToMainWindow5, LV_EVENT_ALL, NULL);

}
