// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void anima_Animation( lv_obj_t *TargetObject, int delay);
// SCREEN: ui_Main_Window
void ui_Main_Window_screen_init(void);
void ui_event_Main_Window( lv_event_t * e);
extern lv_obj_t *ui_Main_Window;
extern lv_obj_t *ui_Header_Main;
extern lv_obj_t *ui_Header_Main_Text;
extern lv_obj_t *ui_Header_Main_Time;
extern lv_obj_t *ui_Header_Main_Volume_Img;
extern lv_obj_t *ui_Header_Main_Volume_Value;
extern lv_obj_t *ui_Menu_Items;
extern lv_obj_t *ui_Music;
void ui_event_Music_Btn( lv_event_t * e);
extern lv_obj_t *ui_Music_Btn;
extern lv_obj_t *ui_Music_Image;
extern lv_obj_t *ui_Music_Text;
extern lv_obj_t *ui_Nature_Sound;
void ui_event_Nature_Sound_Btn( lv_event_t * e);
extern lv_obj_t *ui_Nature_Sound_Btn;
extern lv_obj_t *ui_Nature_Sound_Img;
extern lv_obj_t *ui_Nature_Sound_Text;
extern lv_obj_t *ui_Bluetooth;
void ui_event_Music_Button2( lv_event_t * e);
extern lv_obj_t *ui_Music_Button2;
extern lv_obj_t *ui_Bluetooth_Img;
extern lv_obj_t *ui_Bluetoth_Text;
extern lv_obj_t *ui_Mode;
void ui_event_Mode_Btn( lv_event_t * e);
extern lv_obj_t *ui_Mode_Btn;
extern lv_obj_t *ui_Mode_Img;
extern lv_obj_t *ui_Mode_Text;
extern lv_obj_t *ui_Wake_up;
void ui_event_Wake_up_Btn( lv_event_t * e);
extern lv_obj_t *ui_Wake_up_Btn;
extern lv_obj_t *ui_Weke_up_Img;
extern lv_obj_t *ui_Weke_up_Text;
extern lv_obj_t *ui_Guide;
void ui_event_Guide_Btn( lv_event_t * e);
extern lv_obj_t *ui_Guide_Btn;
extern lv_obj_t *ui_Guide_Img;
extern lv_obj_t *ui_Guide_Text;
extern lv_obj_t *ui_Logo;
// SCREEN: ui_Music_Window
void ui_Music_Window_screen_init(void);
void ui_event_Music_Window( lv_event_t * e);
extern lv_obj_t *ui_Music_Window;
extern lv_obj_t *ui_Header_Music;
extern lv_obj_t *ui_Header_Music_Text;
extern lv_obj_t *ui_Header_Music_Time;
extern lv_obj_t *ui_Header_Music_Volume_Img;
extern lv_obj_t *ui_Header_Music_Volume_Value;
void ui_event_BackToMainWindow( lv_event_t * e);
extern lv_obj_t *ui_BackToMainWindow;
// SCREEN: ui_Nature_Sound_Window
void ui_Nature_Sound_Window_screen_init(void);
extern lv_obj_t *ui_Nature_Sound_Window;
extern lv_obj_t *ui_Header_Nature_Sound;
extern lv_obj_t *ui_Header_Nature_Sound_Text;
extern lv_obj_t *ui_Header_Nature_Sound_Time;
extern lv_obj_t *ui_Header_Nature_Sound_Volume_Img;
extern lv_obj_t *ui_Header_Nature_Sound_Volume_Value;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_Bird_Sound;
extern lv_obj_t *ui_Bird_Sound_Btn;
extern lv_obj_t *ui_Bird_Sound_Img;
extern lv_obj_t *ui_Bird_Sound_Text;
extern lv_obj_t *ui_Bug_Sound;
extern lv_obj_t *ui_Bug_Sound_Btn;
extern lv_obj_t *ui_Bug_Sound_Img;
extern lv_obj_t *ui_Bug_Sound_Text;
extern lv_obj_t *ui_Forest_Sound;
extern lv_obj_t *ui_Forest_Sound_Btn;
extern lv_obj_t *ui_Forest_Sound_Img;
extern lv_obj_t *ui_Forest_Sound_Text;
extern lv_obj_t *ui_Sea_Sound;
extern lv_obj_t *ui_Sea_Sound_Btn;
extern lv_obj_t *ui_Sea_Sound_Img;
extern lv_obj_t *ui_Sea_Sound_Text;
void ui_event_BackToMainWindow2( lv_event_t * e);
extern lv_obj_t *ui_BackToMainWindow2;
// SCREEN: ui_Bluetooth_WIndow
void ui_Bluetooth_WIndow_screen_init(void);
extern lv_obj_t *ui_Bluetooth_WIndow;
extern lv_obj_t *ui_Header_Bluetooth;
extern lv_obj_t *ui_Header_Bluetooth_Text;
extern lv_obj_t *ui_Header_Bluetooth_Time;
extern lv_obj_t *ui_Header_Bluetooth_Volume_Img;
extern lv_obj_t *ui_Header_Bluetooth_Volume_Value;
extern lv_obj_t *ui_Bluetooth_Name;
extern lv_obj_t *ui_Bluetooth_Name_Text;
extern lv_obj_t *ui_Bluetooth_Name_Line;
extern lv_obj_t *ui_Bluetooth_Name_Value;
extern lv_obj_t *ui_Bluetooth_Password;
extern lv_obj_t *ui_Bluetooth_Password_Text;
extern lv_obj_t *ui_Bluetooth_Password_Line;
extern lv_obj_t *ui_Bluetooth_Password_Value;
extern lv_obj_t *ui_Bluetooth_Guide_Text;
void ui_event_BackToMainWindow3( lv_event_t * e);
extern lv_obj_t *ui_BackToMainWindow3;
// SCREEN: ui_Mode_WIndow
void ui_Mode_WIndow_screen_init(void);
extern lv_obj_t *ui_Mode_WIndow;
extern lv_obj_t *ui_Header_Bluetooth2;
extern lv_obj_t *ui_Header_Bluetooth_Text2;
extern lv_obj_t *ui_Header_Bluetooth_Time2;
extern lv_obj_t *ui_Header_Bluetooth_Volume_Img2;
extern lv_obj_t *ui_Header_Bluetooth_Volume_Value2;
extern lv_obj_t *ui_Menu_Items2;
extern lv_obj_t *ui_Music2;
extern lv_obj_t *ui_Music_Image2;
void ui_event_Music_Btn2( lv_event_t * e);
extern lv_obj_t *ui_Music_Btn2;
extern lv_obj_t *ui_Music_Text2;
extern lv_obj_t *ui_Music1;
extern lv_obj_t *ui_Music_Image3;
void ui_event_Music_Btn1( lv_event_t * e);
extern lv_obj_t *ui_Music_Btn1;
extern lv_obj_t *ui_Music_Text1;
extern lv_obj_t *ui_Music3;
extern lv_obj_t *ui_Music_Image4;
void ui_event_Music_Btn3( lv_event_t * e);
extern lv_obj_t *ui_Music_Btn3;
extern lv_obj_t *ui_Music_Text3;
extern lv_obj_t *ui_Music4;
extern lv_obj_t *ui_Music_Image5;
void ui_event_Music_Btn4( lv_event_t * e);
extern lv_obj_t *ui_Music_Btn4;
extern lv_obj_t *ui_Music_Text4;
extern lv_obj_t *ui_Music5;
extern lv_obj_t *ui_Music_Image6;
void ui_event_Music_Btn5( lv_event_t * e);
extern lv_obj_t *ui_Music_Btn5;
extern lv_obj_t *ui_Music_Text5;
extern lv_obj_t *ui_Music6;
extern lv_obj_t *ui_Music_Image7;
void ui_event_Music_Btn6( lv_event_t * e);
extern lv_obj_t *ui_Music_Btn6;
extern lv_obj_t *ui_Music_Text6;
void ui_event_BackToMainWindow4( lv_event_t * e);
extern lv_obj_t *ui_BackToMainWindow4;
// SCREEN: ui_Wake_up_Window
void ui_Wake_up_Window_screen_init(void);
extern lv_obj_t *ui_Wake_up_Window;
extern lv_obj_t *ui_Header_Bluetooth3;
extern lv_obj_t *ui_Header_Bluetooth_Text3;
extern lv_obj_t *ui_Header_Bluetooth_Time3;
extern lv_obj_t *ui_Header_Bluetooth_Volume_Img3;
extern lv_obj_t *ui_Header_Bluetooth_Volume_Value3;
extern lv_obj_t *ui_Bluetooth_Name2;
extern lv_obj_t *ui_Bluetooth_Name_Text2;
extern lv_obj_t *ui_Bluetooth_Name_Line4;
extern lv_obj_t *ui_Bluetooth_Name1;
extern lv_obj_t *ui_Bluetooth_Name_Text1;
extern lv_obj_t *ui_Bluetooth_Name_Line1;
void ui_event_BackToMainWindow5( lv_event_t * e);
extern lv_obj_t *ui_BackToMainWindow5;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Image3;
// SCREEN: ui_Guide_Window
void ui_Guide_Window_screen_init(void);
void ui_event_Guide_Window( lv_event_t * e);
extern lv_obj_t *ui_Guide_Window;
extern lv_obj_t *ui_Header_Bluetooth4;
extern lv_obj_t *ui_Header_Bluetooth_Text4;
extern lv_obj_t *ui_Header_Bluetooth_Time4;
extern lv_obj_t *ui_Header_Bluetooth_Volume_Img4;
extern lv_obj_t *ui_Header_Bluetooth_Volume_Value4;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Popup_WIndow;
void ui_event_Close_More_Info_Btn( lv_event_t * e);
extern lv_obj_t *ui_Close_More_Info_Btn;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Image1;
void ui_event_BackToMainWindow6( lv_event_t * e);
extern lv_obj_t *ui_BackToMainWindow6;
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_861711258);   // assets/丽枫UI/background.png
LV_IMG_DECLARE( ui_img_490182776);   // assets/丽枫UI/音量.png
LV_IMG_DECLARE( ui_img_2087007852);   // assets/丽枫UI/音乐库.png
LV_IMG_DECLARE( ui_img_227802216);   // assets/丽枫UI/自然之音.png
LV_IMG_DECLARE( ui_img_907415264);   // assets/丽枫UI/蓝牙.png
LV_IMG_DECLARE( ui_img_501316714);   // assets/丽枫UI/模式.png
LV_IMG_DECLARE( ui_img_967182345);   // assets/丽枫UI/叫醒服务.png
LV_IMG_DECLARE( ui_img_72497716);   // assets/丽枫UI/指南.png
LV_IMG_DECLARE( ui_img_411136687);   // assets/丽枫UI/lifeng.png
LV_IMG_DECLARE( ui_img_348826415);   // assets/丽枫UI/back.png
LV_IMG_DECLARE( ui_img_12669592);   // assets/丽枫UI/鸟叫.png
LV_IMG_DECLARE( ui_img_2034599484);   // assets/丽枫UI/虫鸣.png
LV_IMG_DECLARE( ui_img_304460963);   // assets/丽枫UI/森林.png
LV_IMG_DECLARE( ui_img_1893023884);   // assets/丽枫UI/大海.png
LV_IMG_DECLARE( ui_img_720053126);   // assets/丽枫UI/N.png
LV_IMG_DECLARE( ui_img_720048778);   // assets/丽枫UI/J.png
LV_IMG_DECLARE( ui_img_720023698);   // assets/丽枫UI/R.png
LV_IMG_DECLARE( ui_img_720017300);   // assets/丽枫UI/P.png
LV_IMG_DECLARE( ui_img_720032643);   // assets/丽枫UI/C.png
LV_IMG_DECLARE( ui_img_720045703);   // assets/丽枫UI/O.png
LV_IMG_DECLARE( ui_img_1526512104);   // assets/丽枫UI/close.png


LV_FONT_DECLARE( ui_font_LanTIng20);
LV_FONT_DECLARE( ui_font_LanTing18);
LV_FONT_DECLARE( ui_font_LanTingFine24);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
